//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUDIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Выручка
    {
        public Nullable<decimal> Выручка_от_реализации { get; set; }
        public Nullable<decimal> Внереализационные_доходы { get; set; }
        public string Содержание_операции { get; set; }
        public Nullable<System.DateTime> Дата_записи { get; set; }
        public int ID { get; set; }
        public Nullable<int> Документ_выручка { get; set; }
        public Nullable<bool> DEL { get; set; }
    
        public virtual Документ Документ { get; set; }
    }
}
