//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUDIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Выплаты
    {
        public Выплаты()
        {
            this.Выплата_работнику = new HashSet<Выплата_работнику>();
        }
    
        public int Код_выплаты { get; set; }
        public string Причина { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public Nullable<System.DateTime> Период_Начало { get; set; }
        public Nullable<System.DateTime> Период_Конец { get; set; }
        public Nullable<bool> Начисляются_страх_взносы { get; set; }
        public Nullable<bool> Начисляются_пенс_взносы { get; set; }
        public bool DEL { get; set; }
    
        public virtual ICollection<Выплата_работнику> Выплата_работнику { get; set; }
    }
}
