//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUDIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Документ
    {
        public Документ()
        {
            this.Выручка = new HashSet<Выручка>();
            this.НДС = new HashSet<НДС>();
            this.Кредитор = new HashSet<Кредитор>();
            this.Товары_из_ТС = new HashSet<Товары_из_ТС>();
            this.Отгрузка_товаров = new HashSet<Отгрузка_товаров>();
            this.Отгрузка_товаров1 = new HashSet<Отгрузка_товаров>();
            this.Строение = new HashSet<Строение>();
            this.Строение1 = new HashSet<Строение>();
            this.Строение2 = new HashSet<Строение>();
        }
    
        public int DocumentID { get; set; }
        public string Номер { get; set; }
        public string Наименование { get; set; }
        public Nullable<bool> DEL { get; set; }
        public System.DateTime Дата { get; set; }
    
        public virtual ICollection<Выручка> Выручка { get; set; }
        public virtual ICollection<НДС> НДС { get; set; }
        public virtual ICollection<Кредитор> Кредитор { get; set; }
        public virtual ICollection<Товары_из_ТС> Товары_из_ТС { get; set; }
        public virtual ICollection<Отгрузка_товаров> Отгрузка_товаров { get; set; }
        public virtual ICollection<Отгрузка_товаров> Отгрузка_товаров1 { get; set; }
        public virtual ICollection<Строение> Строение { get; set; }
        public virtual ICollection<Строение> Строение1 { get; set; }
        public virtual ICollection<Строение> Строение2 { get; set; }
    }
}
