//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUDIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Кредитор
    {
        public int ID { get; set; }
        public string Название { get; set; }
        public Nullable<decimal> Сумма_бр { get; set; }
        public string Номер_договора { get; set; }
        public string Предмет_договора { get; set; }
        public Nullable<System.DateTime> Дата_договора { get; set; }
        public string Наим_валюты { get; set; }
        public Nullable<decimal> Сумма_в_валюте { get; set; }
        public Nullable<int> Документ_задолженность { get; set; }
        public bool DEL { get; set; }
    
        public virtual Документ Документ { get; set; }
    }
}
