//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUDIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Налоги_на_дивиденты
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Дата_начисления_дивидентов { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public string Наименование_организации { get; set; }
        public Nullable<decimal> Налоговая_база { get; set; }
        public Nullable<int> Ставка_налога { get; set; }
        public bool DEL { get; set; }
        public Nullable<int> ID_платежный_док { get; set; }
    
        public virtual Платежный_документ Платежный_документ { get; set; }
    }
}
