//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUDIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Налоговые_вычеты
    {
        public Налоговые_вычеты()
        {
            this.Налоговый_вычет_работника = new HashSet<Налоговый_вычет_работника>();
        }
    
        public int Код_вычета { get; set; }
        public string Тип_вычета { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public Nullable<System.DateTime> Период_Начало { get; set; }
        public Nullable<System.DateTime> Период_Конец { get; set; }
        public bool DEL { get; set; }
    
        public virtual ICollection<Налоговый_вычет_работника> Налоговый_вычет_работника { get; set; }
    }
}
