//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUDIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Налоговый_вычет_работника
    {
        public int Код_вычета { get; set; }
        public int работникID { get; set; }
        public bool DEL { get; set; }
    
        public virtual Налоговые_вычеты Налоговые_вычеты { get; set; }
        public virtual Работник Работник { get; set; }
    }
}
