//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUDIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Налоговый_агент
    {
        public int ID { get; set; }
        public string Наимен_организации { get; set; }
        public string Страна { get; set; }
        public string Вид_дохода { get; set; }
        public Nullable<System.DateTime> Дата_платежа { get; set; }
        public Nullable<decimal> Сумма_платежа { get; set; }
        public Nullable<decimal> Сумма_затрат_для_налога { get; set; }
        public Nullable<decimal> Сумма_освоб_от_налога_РБ { get; set; }
        public Nullable<decimal> Сумма_освоб_от_налога_международн { get; set; }
        public Nullable<short> Ставка_налога_РБ { get; set; }
        public Nullable<int> Ставка_налога_международн { get; set; }
        public bool DEL { get; set; }
        public Nullable<int> ID_платежный_док { get; set; }
    
        public virtual Платежный_документ Платежный_документ { get; set; }
    }
}
