//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUDIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class НДС
    {
        public int ID { get; set; }
        public Nullable<bool> Уплачено_при_приобретении { get; set; }
        public Nullable<int> НДС1 { get; set; }
        public string Наим_прод_покуп { get; set; }
        public Nullable<System.DateTime> Дата_оплаты { get; set; }
        public string Номер_док_оплаты { get; set; }
        public string Уч_номер_плательщ { get; set; }
        public Nullable<decimal> Стоим_с_НДС { get; set; }
        public Nullable<decimal> Стоим_освоб_от_НДС_всего { get; set; }
        public Nullable<decimal> Оборот_за_пределами_РБ { get; set; }
        public Nullable<int> Документ_приобр_поставщ { get; set; }
        public bool DEL { get; set; }
    
        public virtual Документ Документ { get; set; }
    }
}
