//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUDIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Незавершенное_строение
    {
        public int ID { get; set; }
        public string Наименование { get; set; }
        public string Адрес { get; set; }
        public Nullable<System.DateTime> Дата_на_которую_истек_нормат_срок { get; set; }
        public string Нормативный_срок { get; set; }
        public Nullable<decimal> Сумма_затрат { get; set; }
        public Nullable<System.DateTime> Дата_акта_приемки { get; set; }
        public bool DEL { get; set; }
    }
}
