//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUDIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отгрузка_товаров
    {
        public string Лицо_которому_реализуется_товар { get; set; }
        public Nullable<bool> Предоплачено { get; set; }
        public Nullable<System.DateTime> Дата_отгрузки_предоплаты { get; set; }
        public int ID { get; set; }
        public Nullable<decimal> Стоимость_в_бр { get; set; }
        public Nullable<decimal> Стоимость_в_валюте { get; set; }
        public Nullable<decimal> Сумма_оплаты_отгр { get; set; }
        public string Наименование_валюты { get; set; }
        public Nullable<int> Документ_отгр_опл { get; set; }
        public Nullable<int> Документ_опл_отгр { get; set; }
        public bool DEL { get; set; }
    
        public virtual Документ Документ { get; set; }
        public virtual Документ Документ1 { get; set; }
    }
}
