//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUDIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Платежный_документ
    {
        public Платежный_документ()
        {
            this.Налоги_на_дивиденты = new HashSet<Налоги_на_дивиденты>();
            this.Налоговый_агент = new HashSet<Налоговый_агент>();
            this.Пенсионный_взнос = new HashSet<Пенсионный_взнос>();
            this.Подоходный_налог = new HashSet<Подоходный_налог>();
            this.Страховой_взнос = new HashSet<Страховой_взнос>();
        }
    
        public string Номер_платежного_документа { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public bool DEL { get; set; }
        public int ID_платежный_док { get; set; }
    
        public virtual ICollection<Налоги_на_дивиденты> Налоги_на_дивиденты { get; set; }
        public virtual ICollection<Налоговый_агент> Налоговый_агент { get; set; }
        public virtual ICollection<Пенсионный_взнос> Пенсионный_взнос { get; set; }
        public virtual ICollection<Подоходный_налог> Подоходный_налог { get; set; }
        public virtual ICollection<Страховой_взнос> Страховой_взнос { get; set; }
    }
}
