//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUDIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пособия
    {
        public Пособия()
        {
            this.Пособие_работника = new HashSet<Пособие_работника>();
        }
    
        public int Код_пособия { get; set; }
        public string Причина { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public Nullable<System.DateTime> Период_Начало { get; set; }
        public Nullable<System.DateTime> Период_Конец { get; set; }
        public bool DEL { get; set; }
    
        public virtual ICollection<Пособие_работника> Пособие_работника { get; set; }
    }
}
