//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUDIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Подоходный_налог
    {
        public System.DateTime Дата { get; set; }
        public Nullable<decimal> Начислено { get; set; }
        public int работникID { get; set; }
        public Nullable<bool> DEL { get; set; }
        public Nullable<int> ID_платежный_док { get; set; }
    
        public virtual Платежный_документ Платежный_документ { get; set; }
        public virtual Работник Работник { get; set; }
    }
}
