//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUDIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Производственный_кооператив
    {
        public int ID { get; set; }
        public string ФИО { get; set; }
        public Nullable<decimal> Размер_пая { get; set; }
        public Nullable<decimal> Размер_паевых_взносов { get; set; }
        public Nullable<decimal> Выплачена_стоимость_пая { get; set; }
        public Nullable<decimal> Выдано_иное_имущество { get; set; }
        public Nullable<decimal> Иные_выплаты_при_выходе_из_кооператива { get; set; }
        public bool DEL { get; set; }
    }
}
