//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUDIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Работник
    {
        public Работник()
        {
            this.Выплата_работнику = new HashSet<Выплата_работнику>();
            this.Налоговый_вычет_работника = new HashSet<Налоговый_вычет_работника>();
            this.Пенсионный_взнос = new HashSet<Пенсионный_взнос>();
            this.Подоходный_налог = new HashSet<Подоходный_налог>();
            this.Пособие_работника = new HashSet<Пособие_работника>();
            this.Страховой_взнос = new HashSet<Страховой_взнос>();
            this.Удержания = new HashSet<Удержания>();
        }
    
        public string Номер_договора { get; set; }
        public string ФИО { get; set; }
        public Nullable<System.DateTime> Дата_договора { get; set; }
        public string Условия_договора { get; set; }
        public int работникID { get; set; }
        public string Инвалидность { get; set; }
        public Nullable<System.DateTime> Дата_выплаты_вознаграждения { get; set; }
        public Nullable<short> Тариф_пенс_взносов { get; set; }
        public bool DEL { get; set; }
    
        public virtual ICollection<Выплата_работнику> Выплата_работнику { get; set; }
        public virtual ICollection<Налоговый_вычет_работника> Налоговый_вычет_работника { get; set; }
        public virtual ICollection<Пенсионный_взнос> Пенсионный_взнос { get; set; }
        public virtual ICollection<Подоходный_налог> Подоходный_налог { get; set; }
        public virtual ICollection<Пособие_работника> Пособие_работника { get; set; }
        public virtual ICollection<Страховой_взнос> Страховой_взнос { get; set; }
        public virtual ICollection<Удержания> Удержания { get; set; }
    }
}
