//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUDIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Строение
    {
        public Строение()
        {
            this.Стоимость_строения = new HashSet<Стоимость_строения>();
        }
    
        public int ID { get; set; }
        public string Наименование { get; set; }
        public string Адрес { get; set; }
        public Nullable<System.DateTime> Дата_приобретения { get; set; }
        public Nullable<System.DateTime> Дата_гос_регистрации { get; set; }
        public Nullable<System.DateTime> Дата_ввода_в_эксплуатацию { get; set; }
        public Nullable<System.DateTime> Дата_выбытия { get; set; }
        public Nullable<int> Документ_приобретение { get; set; }
        public Nullable<int> Документ_регистрация { get; set; }
        public Nullable<int> Документ_выбытие { get; set; }
        public Nullable<byte> Право { get; set; }
        public bool DEL { get; set; }
    
        public virtual Документ Документ { get; set; }
        public virtual Документ Документ1 { get; set; }
        public virtual Документ Документ2 { get; set; }
        public virtual ICollection<Стоимость_строения> Стоимость_строения { get; set; }
    }
}
