//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUDIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Стоимость_строения
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Период { get; set; }
        public Nullable<int> Площадь_всего { get; set; }
        public Nullable<int> Площадь_аренда { get; set; }
        public Nullable<decimal> Первоначальная_стоимость { get; set; }
        public Nullable<decimal> Сумма_армотизации { get; set; }
        public int ID_строение { get; set; }
        public bool DEL { get; set; }
    
        public virtual Строение Строение { get; set; }
    }
}
