//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUDIR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары_из_ТС
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public string Серия_транспортного_документа { get; set; }
        public string Номер_транспортного_документа { get; set; }
        public Nullable<System.DateTime> Дата_транспортного_документа { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
        public Nullable<int> Счет_фактура { get; set; }
        public bool DEL { get; set; }
    
        public virtual Документ Документ { get; set; }
    }
}
