#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KUDIR")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertВыручка(Выручка instance);
    partial void UpdateВыручка(Выручка instance);
    partial void DeleteВыручка(Выручка instance);
    partial void InsertКредитор(Кредитор instance);
    partial void UpdateКредитор(Кредитор instance);
    partial void DeleteКредитор(Кредитор instance);
    partial void InsertУдержания(Удержания instance);
    partial void UpdateУдержания(Удержания instance);
    partial void DeleteУдержания(Удержания instance);
    partial void InsertРаботник(Работник instance);
    partial void UpdateРаботник(Работник instance);
    partial void DeleteРаботник(Работник instance);
    partial void InsertПроизводственный_кооператив(Производственный_кооператив instance);
    partial void UpdateПроизводственный_кооператив(Производственный_кооператив instance);
    partial void DeleteПроизводственный_кооператив(Производственный_кооператив instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::Reports.Properties.Settings.Default.KUDIRConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Выручка> Выручкаs
		{
			get
			{
				return this.GetTable<Выручка>();
			}
		}
		
		public System.Data.Linq.Table<view_Отгрузка> view_Отгрузкаs
		{
			get
			{
				return this.GetTable<view_Отгрузка>();
			}
		}
		
		public System.Data.Linq.Table<view_Предоплата> view_Предоплатаs
		{
			get
			{
				return this.GetTable<view_Предоплата>();
			}
		}
		
		public System.Data.Linq.Table<Кредитор> Кредиторs
		{
			get
			{
				return this.GetTable<Кредитор>();
			}
		}
		
		public System.Data.Linq.Table<view_Выплаты> view_Выплатыs
		{
			get
			{
				return this.GetTable<view_Выплаты>();
			}
		}
		
		public System.Data.Linq.Table<view_Вычет> view_Вычетs
		{
			get
			{
				return this.GetTable<view_Вычет>();
			}
		}
		
		public System.Data.Linq.Table<Удержания> Удержанияs
		{
			get
			{
				return this.GetTable<Удержания>();
			}
		}
		
		public System.Data.Linq.Table<Работник> Работникs
		{
			get
			{
				return this.GetTable<Работник>();
			}
		}
		
		public System.Data.Linq.Table<view_Зарплаты> view_Зарплатыs
		{
			get
			{
				return this.GetTable<view_Зарплаты>();
			}
		}
		
		public System.Data.Linq.Table<view_ПодоходныйНалогПеречисл> view_ПодоходныйНалогПеречислs
		{
			get
			{
				return this.GetTable<view_ПодоходныйНалогПеречисл>();
			}
		}
		
		public System.Data.Linq.Table<view_Дивиденты> view_Дивидентыs
		{
			get
			{
				return this.GetTable<view_Дивиденты>();
			}
		}
		
		public System.Data.Linq.Table<view_НалоговыйАгент> view_НалоговыйАгентs
		{
			get
			{
				return this.GetTable<view_НалоговыйАгент>();
			}
		}
		
		public System.Data.Linq.Table<Производственный_кооператив> Производственный_кооперативs
		{
			get
			{
				return this.GetTable<Производственный_кооператив>();
			}
		}
		
		public System.Data.Linq.Table<view_СтрахВзнос> view_СтрахВзносs
		{
			get
			{
				return this.GetTable<view_СтрахВзнос>();
			}
		}
		
		public System.Data.Linq.Table<view_ПенсВзносы> view_ПенсВзносыs
		{
			get
			{
				return this.GetTable<view_ПенсВзносы>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.СуммыВычетов")]
		public int СуммыВычетов([global::System.Data.Linq.Mapping.ParameterAttribute(Name="РаботникID", DbType="Int")] System.Nullable<int> работникID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Дата", DbType="DateTime")] System.Nullable<System.DateTime> дата, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Стандартные", DbType="Money")] ref System.Nullable<decimal> стандартные, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Социальные", DbType="Money")] ref System.Nullable<decimal> социальные, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Имущественные", DbType="Money")] ref System.Nullable<decimal> имущественные, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Профессиональные", DbType="Money")] ref System.Nullable<decimal> профессиональные, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ОсвобождаемыеДоходы", DbType="Money")] ref System.Nullable<decimal> освобождаемыеДоходы)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), работникID, дата, стандартные, социальные, имущественные, профессиональные, освобождаемыеДоходы);
			стандартные = ((System.Nullable<decimal>)(result.GetParameterValue(2)));
			социальные = ((System.Nullable<decimal>)(result.GetParameterValue(3)));
			имущественные = ((System.Nullable<decimal>)(result.GetParameterValue(4)));
			профессиональные = ((System.Nullable<decimal>)(result.GetParameterValue(5)));
			освобождаемыеДоходы = ((System.Nullable<decimal>)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.СтандартныеПособия")]
		public int СтандартныеПособия([global::System.Data.Linq.Mapping.ParameterAttribute(Name="РаботникID", DbType="Int")] System.Nullable<int> работникID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Дата", DbType="DateTime")] System.Nullable<System.DateTime> дата, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ПоВремНетрудосп", DbType="Money")] ref System.Nullable<decimal> поВремНетрудосп, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ПоБеремИРодам", DbType="Money")] ref System.Nullable<decimal> поБеремИРодам, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Единовременное", DbType="Money")] ref System.Nullable<decimal> единовременное, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ПоУходуЗаРебенком", DbType="Money")] ref System.Nullable<decimal> поУходуЗаРебенком, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Опекуну", DbType="Money")] ref System.Nullable<decimal> опекуну, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="НаДетей", DbType="Money")] ref System.Nullable<decimal> наДетей, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="РождениеРебенка", DbType="Money")] ref System.Nullable<decimal> рождениеРебенка, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ЖенщинамУчетБеременность", DbType="Money")] ref System.Nullable<decimal> женщинамУчетБеременность, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Погребение", DbType="Money")] ref System.Nullable<decimal> погребение)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), работникID, дата, поВремНетрудосп, поБеремИРодам, единовременное, поУходуЗаРебенком, опекуну, наДетей, рождениеРебенка, женщинамУчетБеременность, погребение);
			поВремНетрудосп = ((System.Nullable<decimal>)(result.GetParameterValue(2)));
			поБеремИРодам = ((System.Nullable<decimal>)(result.GetParameterValue(3)));
			единовременное = ((System.Nullable<decimal>)(result.GetParameterValue(4)));
			поУходуЗаРебенком = ((System.Nullable<decimal>)(result.GetParameterValue(5)));
			опекуну = ((System.Nullable<decimal>)(result.GetParameterValue(6)));
			наДетей = ((System.Nullable<decimal>)(result.GetParameterValue(7)));
			рождениеРебенка = ((System.Nullable<decimal>)(result.GetParameterValue(8)));
			женщинамУчетБеременность = ((System.Nullable<decimal>)(result.GetParameterValue(9)));
			погребение = ((System.Nullable<decimal>)(result.GetParameterValue(10)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Выручка")]
	public partial class Выручка : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<decimal> _Выручка_от_реализации;
		
		private System.Nullable<decimal> _Внереализационные_доходы;
		
		private string _Содержание_операции;
		
		private System.Nullable<System.DateTime> _Дата_записи;
		
		private int _ID;
		
		private bool _DEL;
		
		private string _Док_выручка_Наим;
		
		private string _Док_выручка_Номер;
		
		private System.Nullable<System.DateTime> _Док_выручка_Дата;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnВыручка_от_реализацииChanging(System.Nullable<decimal> value);
    partial void OnВыручка_от_реализацииChanged();
    partial void OnВнереализационные_доходыChanging(System.Nullable<decimal> value);
    partial void OnВнереализационные_доходыChanged();
    partial void OnСодержание_операцииChanging(string value);
    partial void OnСодержание_операцииChanged();
    partial void OnДата_записиChanging(System.Nullable<System.DateTime> value);
    partial void OnДата_записиChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDELChanging(bool value);
    partial void OnDELChanged();
    partial void OnДок_выручка_НаимChanging(string value);
    partial void OnДок_выручка_НаимChanged();
    partial void OnДок_выручка_НомерChanging(string value);
    partial void OnДок_выручка_НомерChanged();
    partial void OnДок_выручка_ДатаChanging(System.Nullable<System.DateTime> value);
    partial void OnДок_выручка_ДатаChanged();
    #endregion
		
		public Выручка()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Выручка_от_реализации", DbType="Money")]
		public System.Nullable<decimal> Выручка_от_реализации
		{
			get
			{
				return this._Выручка_от_реализации;
			}
			set
			{
				if ((this._Выручка_от_реализации != value))
				{
					this.OnВыручка_от_реализацииChanging(value);
					this.SendPropertyChanging();
					this._Выручка_от_реализации = value;
					this.SendPropertyChanged("Выручка_от_реализации");
					this.OnВыручка_от_реализацииChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Внереализационные_доходы", DbType="Money")]
		public System.Nullable<decimal> Внереализационные_доходы
		{
			get
			{
				return this._Внереализационные_доходы;
			}
			set
			{
				if ((this._Внереализационные_доходы != value))
				{
					this.OnВнереализационные_доходыChanging(value);
					this.SendPropertyChanging();
					this._Внереализационные_доходы = value;
					this.SendPropertyChanged("Внереализационные_доходы");
					this.OnВнереализационные_доходыChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Содержание_операции", DbType="VarChar(80)")]
		public string Содержание_операции
		{
			get
			{
				return this._Содержание_операции;
			}
			set
			{
				if ((this._Содержание_операции != value))
				{
					this.OnСодержание_операцииChanging(value);
					this.SendPropertyChanging();
					this._Содержание_операции = value;
					this.SendPropertyChanged("Содержание_операции");
					this.OnСодержание_операцииChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Дата_записи", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_записи
		{
			get
			{
				return this._Дата_записи;
			}
			set
			{
				if ((this._Дата_записи != value))
				{
					this.OnДата_записиChanging(value);
					this.SendPropertyChanging();
					this._Дата_записи = value;
					this.SendPropertyChanged("Дата_записи");
					this.OnДата_записиChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEL", DbType="Bit NOT NULL")]
		public bool DEL
		{
			get
			{
				return this._DEL;
			}
			set
			{
				if ((this._DEL != value))
				{
					this.OnDELChanging(value);
					this.SendPropertyChanging();
					this._DEL = value;
					this.SendPropertyChanged("DEL");
					this.OnDELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Док_выручка_Наим", DbType="VarChar(100)")]
		public string Док_выручка_Наим
		{
			get
			{
				return this._Док_выручка_Наим;
			}
			set
			{
				if ((this._Док_выручка_Наим != value))
				{
					this.OnДок_выручка_НаимChanging(value);
					this.SendPropertyChanging();
					this._Док_выручка_Наим = value;
					this.SendPropertyChanged("Док_выручка_Наим");
					this.OnДок_выручка_НаимChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Док_выручка_Номер", DbType="VarChar(30)")]
		public string Док_выручка_Номер
		{
			get
			{
				return this._Док_выручка_Номер;
			}
			set
			{
				if ((this._Док_выручка_Номер != value))
				{
					this.OnДок_выручка_НомерChanging(value);
					this.SendPropertyChanging();
					this._Док_выручка_Номер = value;
					this.SendPropertyChanged("Док_выручка_Номер");
					this.OnДок_выручка_НомерChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Док_выручка_Дата", DbType="DateTime")]
		public System.Nullable<System.DateTime> Док_выручка_Дата
		{
			get
			{
				return this._Док_выручка_Дата;
			}
			set
			{
				if ((this._Док_выручка_Дата != value))
				{
					this.OnДок_выручка_ДатаChanging(value);
					this.SendPropertyChanging();
					this._Док_выручка_Дата = value;
					this.SendPropertyChanged("Док_выручка_Дата");
					this.OnДок_выручка_ДатаChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_Отгрузка")]
	public partial class view_Отгрузка
	{
		
		private int _ID;
		
		private System.Nullable<System.DateTime> _Дата_отгрузки;
		
		private string _Лицо_которому_реализ_товар;
		
		private string _Наим_док_отгрузки;
		
		private string _Номер_док_отгрузки;
		
		private System.Nullable<System.DateTime> _Дата_док_отгрузки;
		
		private System.Nullable<decimal> _Стоимость_отгр_товаров_в_бр;
		
		private string _Наим_валюты;
		
		private System.Nullable<decimal> _Стоимость_в_валюте;
		
		private string _Наим_док_оплаты;
		
		private string _Номер_док_оплаты;
		
		private System.Nullable<System.DateTime> _Дата_док_оплаты;
		
		private System.Nullable<decimal> _Сумма;
		
		private bool _DEL;
		
		private System.Nullable<bool> _Предоплачено;
		
		private System.Nullable<System.DateTime> _Дата_оплаты;
		
		public view_Отгрузка()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата отгрузки]", Storage="_Дата_отгрузки", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_отгрузки
		{
			get
			{
				return this._Дата_отгрузки;
			}
			set
			{
				if ((this._Дата_отгрузки != value))
				{
					this._Дата_отгрузки = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Лицо которому реализ товар]", Storage="_Лицо_которому_реализ_товар", DbType="VarChar(50)")]
		public string Лицо_которому_реализ_товар
		{
			get
			{
				return this._Лицо_которому_реализ_товар;
			}
			set
			{
				if ((this._Лицо_которому_реализ_товар != value))
				{
					this._Лицо_которому_реализ_товар = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Наим док отгрузки]", Storage="_Наим_док_отгрузки", DbType="VarChar(100)")]
		public string Наим_док_отгрузки
		{
			get
			{
				return this._Наим_док_отгрузки;
			}
			set
			{
				if ((this._Наим_док_отгрузки != value))
				{
					this._Наим_док_отгрузки = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Номер док отгрузки]", Storage="_Номер_док_отгрузки", DbType="VarChar(30)")]
		public string Номер_док_отгрузки
		{
			get
			{
				return this._Номер_док_отгрузки;
			}
			set
			{
				if ((this._Номер_док_отгрузки != value))
				{
					this._Номер_док_отгрузки = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата док отгрузки]", Storage="_Дата_док_отгрузки", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_док_отгрузки
		{
			get
			{
				return this._Дата_док_отгрузки;
			}
			set
			{
				if ((this._Дата_док_отгрузки != value))
				{
					this._Дата_док_отгрузки = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Стоимость отгр товаров в бр]", Storage="_Стоимость_отгр_товаров_в_бр", DbType="Money")]
		public System.Nullable<decimal> Стоимость_отгр_товаров_в_бр
		{
			get
			{
				return this._Стоимость_отгр_товаров_в_бр;
			}
			set
			{
				if ((this._Стоимость_отгр_товаров_в_бр != value))
				{
					this._Стоимость_отгр_товаров_в_бр = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Наим валюты]", Storage="_Наим_валюты", DbType="VarChar(50)")]
		public string Наим_валюты
		{
			get
			{
				return this._Наим_валюты;
			}
			set
			{
				if ((this._Наим_валюты != value))
				{
					this._Наим_валюты = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Стоимость в валюте]", Storage="_Стоимость_в_валюте", DbType="Money")]
		public System.Nullable<decimal> Стоимость_в_валюте
		{
			get
			{
				return this._Стоимость_в_валюте;
			}
			set
			{
				if ((this._Стоимость_в_валюте != value))
				{
					this._Стоимость_в_валюте = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Наим док оплаты]", Storage="_Наим_док_оплаты", DbType="VarChar(100)")]
		public string Наим_док_оплаты
		{
			get
			{
				return this._Наим_док_оплаты;
			}
			set
			{
				if ((this._Наим_док_оплаты != value))
				{
					this._Наим_док_оплаты = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Номер док оплаты]", Storage="_Номер_док_оплаты", DbType="VarChar(30)")]
		public string Номер_док_оплаты
		{
			get
			{
				return this._Номер_док_оплаты;
			}
			set
			{
				if ((this._Номер_док_оплаты != value))
				{
					this._Номер_док_оплаты = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата док оплаты]", Storage="_Дата_док_оплаты", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_док_оплаты
		{
			get
			{
				return this._Дата_док_оплаты;
			}
			set
			{
				if ((this._Дата_док_оплаты != value))
				{
					this._Дата_док_оплаты = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Сумма", DbType="Money")]
		public System.Nullable<decimal> Сумма
		{
			get
			{
				return this._Сумма;
			}
			set
			{
				if ((this._Сумма != value))
				{
					this._Сумма = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEL", DbType="Bit NOT NULL")]
		public bool DEL
		{
			get
			{
				return this._DEL;
			}
			set
			{
				if ((this._DEL != value))
				{
					this._DEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Предоплачено", DbType="Bit")]
		public System.Nullable<bool> Предоплачено
		{
			get
			{
				return this._Предоплачено;
			}
			set
			{
				if ((this._Предоплачено != value))
				{
					this._Предоплачено = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата оплаты]", Storage="_Дата_оплаты", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_оплаты
		{
			get
			{
				return this._Дата_оплаты;
			}
			set
			{
				if ((this._Дата_оплаты != value))
				{
					this._Дата_оплаты = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_Предоплата")]
	public partial class view_Предоплата
	{
		
		private int _ID;
		
		private System.Nullable<System.DateTime> _Дата_предоплаты;
		
		private string _Лицо_которому_реализ_товар;
		
		private string _Наим_док_оплаты;
		
		private string _Номер_док_оплаты;
		
		private System.Nullable<System.DateTime> _Дата_док_оплаты;
		
		private System.Nullable<decimal> _Сумма_предоплаты;
		
		private string _Наим_валюты;
		
		private System.Nullable<decimal> _Сумма_в_валюте;
		
		private string _Наим_док_отгрузки;
		
		private string _Номер_док_отгрузки;
		
		private System.Nullable<System.DateTime> _Дата_док_отгрузки;
		
		private System.Nullable<bool> _Предоплачено;
		
		private bool _DEL;
		
		private System.Nullable<decimal> _Сумма;
		
		private System.Nullable<System.DateTime> _Дата_отгрузки;
		
		public view_Предоплата()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата предоплаты]", Storage="_Дата_предоплаты", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_предоплаты
		{
			get
			{
				return this._Дата_предоплаты;
			}
			set
			{
				if ((this._Дата_предоплаты != value))
				{
					this._Дата_предоплаты = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Лицо которому реализ товар]", Storage="_Лицо_которому_реализ_товар", DbType="VarChar(50)")]
		public string Лицо_которому_реализ_товар
		{
			get
			{
				return this._Лицо_которому_реализ_товар;
			}
			set
			{
				if ((this._Лицо_которому_реализ_товар != value))
				{
					this._Лицо_которому_реализ_товар = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Наим док оплаты]", Storage="_Наим_док_оплаты", DbType="VarChar(100)")]
		public string Наим_док_оплаты
		{
			get
			{
				return this._Наим_док_оплаты;
			}
			set
			{
				if ((this._Наим_док_оплаты != value))
				{
					this._Наим_док_оплаты = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Номер док оплаты]", Storage="_Номер_док_оплаты", DbType="VarChar(30)")]
		public string Номер_док_оплаты
		{
			get
			{
				return this._Номер_док_оплаты;
			}
			set
			{
				if ((this._Номер_док_оплаты != value))
				{
					this._Номер_док_оплаты = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата док оплаты]", Storage="_Дата_док_оплаты", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_док_оплаты
		{
			get
			{
				return this._Дата_док_оплаты;
			}
			set
			{
				if ((this._Дата_док_оплаты != value))
				{
					this._Дата_док_оплаты = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Сумма предоплаты]", Storage="_Сумма_предоплаты", DbType="Money")]
		public System.Nullable<decimal> Сумма_предоплаты
		{
			get
			{
				return this._Сумма_предоплаты;
			}
			set
			{
				if ((this._Сумма_предоплаты != value))
				{
					this._Сумма_предоплаты = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Наим валюты]", Storage="_Наим_валюты", DbType="VarChar(50)")]
		public string Наим_валюты
		{
			get
			{
				return this._Наим_валюты;
			}
			set
			{
				if ((this._Наим_валюты != value))
				{
					this._Наим_валюты = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Сумма в валюте]", Storage="_Сумма_в_валюте", DbType="Money")]
		public System.Nullable<decimal> Сумма_в_валюте
		{
			get
			{
				return this._Сумма_в_валюте;
			}
			set
			{
				if ((this._Сумма_в_валюте != value))
				{
					this._Сумма_в_валюте = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Наим док отгрузки]", Storage="_Наим_док_отгрузки", DbType="VarChar(100)")]
		public string Наим_док_отгрузки
		{
			get
			{
				return this._Наим_док_отгрузки;
			}
			set
			{
				if ((this._Наим_док_отгрузки != value))
				{
					this._Наим_док_отгрузки = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Номер док отгрузки]", Storage="_Номер_док_отгрузки", DbType="VarChar(30)")]
		public string Номер_док_отгрузки
		{
			get
			{
				return this._Номер_док_отгрузки;
			}
			set
			{
				if ((this._Номер_док_отгрузки != value))
				{
					this._Номер_док_отгрузки = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата док отгрузки]", Storage="_Дата_док_отгрузки", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_док_отгрузки
		{
			get
			{
				return this._Дата_док_отгрузки;
			}
			set
			{
				if ((this._Дата_док_отгрузки != value))
				{
					this._Дата_док_отгрузки = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Предоплачено", DbType="Bit")]
		public System.Nullable<bool> Предоплачено
		{
			get
			{
				return this._Предоплачено;
			}
			set
			{
				if ((this._Предоплачено != value))
				{
					this._Предоплачено = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEL", DbType="Bit NOT NULL")]
		public bool DEL
		{
			get
			{
				return this._DEL;
			}
			set
			{
				if ((this._DEL != value))
				{
					this._DEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Сумма", DbType="Money")]
		public System.Nullable<decimal> Сумма
		{
			get
			{
				return this._Сумма;
			}
			set
			{
				if ((this._Сумма != value))
				{
					this._Сумма = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата отгрузки]", Storage="_Дата_отгрузки", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_отгрузки
		{
			get
			{
				return this._Дата_отгрузки;
			}
			set
			{
				if ((this._Дата_отгрузки != value))
				{
					this._Дата_отгрузки = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Кредитор")]
	public partial class Кредитор : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Название;
		
		private System.Nullable<decimal> _Сумма_бр;
		
		private string _Номер_договора;
		
		private string _Предмет_договора;
		
		private System.Nullable<System.DateTime> _Дата_договора;
		
		private string _Наим_валюты;
		
		private System.Nullable<decimal> _Сумма_в_валюте;
		
		private bool _DEL;
		
		private string _Док_задолж_Наим;
		
		private string _Док_задолж_Номер;
		
		private System.Nullable<System.DateTime> _Док_задолж_Дата;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnНазваниеChanging(string value);
    partial void OnНазваниеChanged();
    partial void OnСумма_брChanging(System.Nullable<decimal> value);
    partial void OnСумма_брChanged();
    partial void OnНомер_договораChanging(string value);
    partial void OnНомер_договораChanged();
    partial void OnПредмет_договораChanging(string value);
    partial void OnПредмет_договораChanged();
    partial void OnДата_договораChanging(System.Nullable<System.DateTime> value);
    partial void OnДата_договораChanged();
    partial void OnНаим_валютыChanging(string value);
    partial void OnНаим_валютыChanged();
    partial void OnСумма_в_валютеChanging(System.Nullable<decimal> value);
    partial void OnСумма_в_валютеChanged();
    partial void OnDELChanging(bool value);
    partial void OnDELChanged();
    partial void OnДок_задолж_НаимChanging(string value);
    partial void OnДок_задолж_НаимChanged();
    partial void OnДок_задолж_НомерChanging(string value);
    partial void OnДок_задолж_НомерChanged();
    partial void OnДок_задолж_ДатаChanging(System.Nullable<System.DateTime> value);
    partial void OnДок_задолж_ДатаChanged();
    #endregion
		
		public Кредитор()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Название", DbType="VarChar(80)")]
		public string Название
		{
			get
			{
				return this._Название;
			}
			set
			{
				if ((this._Название != value))
				{
					this.OnНазваниеChanging(value);
					this.SendPropertyChanging();
					this._Название = value;
					this.SendPropertyChanged("Название");
					this.OnНазваниеChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Сумма_бр", DbType="Money")]
		public System.Nullable<decimal> Сумма_бр
		{
			get
			{
				return this._Сумма_бр;
			}
			set
			{
				if ((this._Сумма_бр != value))
				{
					this.OnСумма_брChanging(value);
					this.SendPropertyChanging();
					this._Сумма_бр = value;
					this.SendPropertyChanged("Сумма_бр");
					this.OnСумма_брChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Номер_договора", DbType="VarChar(20)")]
		public string Номер_договора
		{
			get
			{
				return this._Номер_договора;
			}
			set
			{
				if ((this._Номер_договора != value))
				{
					this.OnНомер_договораChanging(value);
					this.SendPropertyChanging();
					this._Номер_договора = value;
					this.SendPropertyChanged("Номер_договора");
					this.OnНомер_договораChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Предмет_договора", DbType="VarChar(200)")]
		public string Предмет_договора
		{
			get
			{
				return this._Предмет_договора;
			}
			set
			{
				if ((this._Предмет_договора != value))
				{
					this.OnПредмет_договораChanging(value);
					this.SendPropertyChanging();
					this._Предмет_договора = value;
					this.SendPropertyChanged("Предмет_договора");
					this.OnПредмет_договораChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Дата_договора", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_договора
		{
			get
			{
				return this._Дата_договора;
			}
			set
			{
				if ((this._Дата_договора != value))
				{
					this.OnДата_договораChanging(value);
					this.SendPropertyChanging();
					this._Дата_договора = value;
					this.SendPropertyChanged("Дата_договора");
					this.OnДата_договораChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Наим_валюты", DbType="VarChar(50)")]
		public string Наим_валюты
		{
			get
			{
				return this._Наим_валюты;
			}
			set
			{
				if ((this._Наим_валюты != value))
				{
					this.OnНаим_валютыChanging(value);
					this.SendPropertyChanging();
					this._Наим_валюты = value;
					this.SendPropertyChanged("Наим_валюты");
					this.OnНаим_валютыChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Сумма_в_валюте", DbType="Money")]
		public System.Nullable<decimal> Сумма_в_валюте
		{
			get
			{
				return this._Сумма_в_валюте;
			}
			set
			{
				if ((this._Сумма_в_валюте != value))
				{
					this.OnСумма_в_валютеChanging(value);
					this.SendPropertyChanging();
					this._Сумма_в_валюте = value;
					this.SendPropertyChanged("Сумма_в_валюте");
					this.OnСумма_в_валютеChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEL", DbType="Bit NOT NULL")]
		public bool DEL
		{
			get
			{
				return this._DEL;
			}
			set
			{
				if ((this._DEL != value))
				{
					this.OnDELChanging(value);
					this.SendPropertyChanging();
					this._DEL = value;
					this.SendPropertyChanged("DEL");
					this.OnDELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Док_задолж_Наим", DbType="VarChar(100)")]
		public string Док_задолж_Наим
		{
			get
			{
				return this._Док_задолж_Наим;
			}
			set
			{
				if ((this._Док_задолж_Наим != value))
				{
					this.OnДок_задолж_НаимChanging(value);
					this.SendPropertyChanging();
					this._Док_задолж_Наим = value;
					this.SendPropertyChanged("Док_задолж_Наим");
					this.OnДок_задолж_НаимChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Док_задолж_Номер", DbType="VarChar(30)")]
		public string Док_задолж_Номер
		{
			get
			{
				return this._Док_задолж_Номер;
			}
			set
			{
				if ((this._Док_задолж_Номер != value))
				{
					this.OnДок_задолж_НомерChanging(value);
					this.SendPropertyChanging();
					this._Док_задолж_Номер = value;
					this.SendPropertyChanged("Док_задолж_Номер");
					this.OnДок_задолж_НомерChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Док_задолж_Дата", DbType="DateTime")]
		public System.Nullable<System.DateTime> Док_задолж_Дата
		{
			get
			{
				return this._Док_задолж_Дата;
			}
			set
			{
				if ((this._Док_задолж_Дата != value))
				{
					this.OnДок_задолж_ДатаChanging(value);
					this.SendPropertyChanging();
					this._Док_задолж_Дата = value;
					this.SendPropertyChanged("Док_задолж_Дата");
					this.OnДок_задолж_ДатаChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_Выплаты")]
	public partial class view_Выплаты
	{
		
		private int _Код_выплаты;
		
		private int _работникID;
		
		private bool _DEL_Выплаты;
		
		private System.Nullable<decimal> _Сумма;
		
		private string _Причина;
		
		private System.Nullable<System.DateTime> _Начало_периода;
		
		private System.Nullable<System.DateTime> _Конец_периода;
		
		private System.Nullable<bool> _Начисляются_страх_взносы;
		
		private System.Nullable<bool> _Начисляются_пенс_взносы;
		
		private bool _DEL_ВыплатыРаботнику;
		
		public view_Выплаты()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Код_выплаты", DbType="Int NOT NULL")]
		public int Код_выплаты
		{
			get
			{
				return this._Код_выплаты;
			}
			set
			{
				if ((this._Код_выплаты != value))
				{
					this._Код_выплаты = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_работникID", DbType="Int NOT NULL")]
		public int работникID
		{
			get
			{
				return this._работникID;
			}
			set
			{
				if ((this._работникID != value))
				{
					this._работникID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEL_Выплаты", DbType="Bit NOT NULL")]
		public bool DEL_Выплаты
		{
			get
			{
				return this._DEL_Выплаты;
			}
			set
			{
				if ((this._DEL_Выплаты != value))
				{
					this._DEL_Выплаты = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Сумма", DbType="Money")]
		public System.Nullable<decimal> Сумма
		{
			get
			{
				return this._Сумма;
			}
			set
			{
				if ((this._Сумма != value))
				{
					this._Сумма = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Причина", DbType="VarChar(150)")]
		public string Причина
		{
			get
			{
				return this._Причина;
			}
			set
			{
				if ((this._Причина != value))
				{
					this._Причина = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Начало периода]", Storage="_Начало_периода", DbType="DateTime")]
		public System.Nullable<System.DateTime> Начало_периода
		{
			get
			{
				return this._Начало_периода;
			}
			set
			{
				if ((this._Начало_периода != value))
				{
					this._Начало_периода = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Конец периода]", Storage="_Конец_периода", DbType="DateTime")]
		public System.Nullable<System.DateTime> Конец_периода
		{
			get
			{
				return this._Конец_периода;
			}
			set
			{
				if ((this._Конец_периода != value))
				{
					this._Конец_периода = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Начисляются страх взносы]", Storage="_Начисляются_страх_взносы", DbType="Bit")]
		public System.Nullable<bool> Начисляются_страх_взносы
		{
			get
			{
				return this._Начисляются_страх_взносы;
			}
			set
			{
				if ((this._Начисляются_страх_взносы != value))
				{
					this._Начисляются_страх_взносы = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Начисляются пенс взносы]", Storage="_Начисляются_пенс_взносы", DbType="Bit")]
		public System.Nullable<bool> Начисляются_пенс_взносы
		{
			get
			{
				return this._Начисляются_пенс_взносы;
			}
			set
			{
				if ((this._Начисляются_пенс_взносы != value))
				{
					this._Начисляются_пенс_взносы = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEL_ВыплатыРаботнику", DbType="Bit NOT NULL")]
		public bool DEL_ВыплатыРаботнику
		{
			get
			{
				return this._DEL_ВыплатыРаботнику;
			}
			set
			{
				if ((this._DEL_ВыплатыРаботнику != value))
				{
					this._DEL_ВыплатыРаботнику = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_Вычет")]
	public partial class view_Вычет
	{
		
		private int _Код_вычета;
		
		private int _работникID;
		
		private bool _DEL_вычет;
		
		private System.Nullable<decimal> _Сумма;
		
		private string _Тип_вычета;
		
		private System.Nullable<System.DateTime> _Начало_периода;
		
		private System.Nullable<System.DateTime> _Конец_периода;
		
		private bool _DEL_вычетРаботника;
		
		public view_Вычет()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Код_вычета", DbType="Int NOT NULL")]
		public int Код_вычета
		{
			get
			{
				return this._Код_вычета;
			}
			set
			{
				if ((this._Код_вычета != value))
				{
					this._Код_вычета = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_работникID", DbType="Int NOT NULL")]
		public int работникID
		{
			get
			{
				return this._работникID;
			}
			set
			{
				if ((this._работникID != value))
				{
					this._работникID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEL_вычет", DbType="Bit NOT NULL")]
		public bool DEL_вычет
		{
			get
			{
				return this._DEL_вычет;
			}
			set
			{
				if ((this._DEL_вычет != value))
				{
					this._DEL_вычет = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Сумма", DbType="Money")]
		public System.Nullable<decimal> Сумма
		{
			get
			{
				return this._Сумма;
			}
			set
			{
				if ((this._Сумма != value))
				{
					this._Сумма = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Тип вычета]", Storage="_Тип_вычета", DbType="VarChar(150)")]
		public string Тип_вычета
		{
			get
			{
				return this._Тип_вычета;
			}
			set
			{
				if ((this._Тип_вычета != value))
				{
					this._Тип_вычета = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Начало периода]", Storage="_Начало_периода", DbType="DateTime")]
		public System.Nullable<System.DateTime> Начало_периода
		{
			get
			{
				return this._Начало_периода;
			}
			set
			{
				if ((this._Начало_периода != value))
				{
					this._Начало_периода = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Конец периода]", Storage="_Конец_периода", DbType="DateTime")]
		public System.Nullable<System.DateTime> Конец_периода
		{
			get
			{
				return this._Конец_периода;
			}
			set
			{
				if ((this._Конец_периода != value))
				{
					this._Конец_периода = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEL_вычетРаботника", DbType="Bit NOT NULL")]
		public bool DEL_вычетРаботника
		{
			get
			{
				return this._DEL_вычетРаботника;
			}
			set
			{
				if ((this._DEL_вычетРаботника != value))
				{
					this._DEL_вычетРаботника = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Удержания")]
	public partial class Удержания : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _работникID;
		
		private System.DateTime _Дата;
		
		private System.Nullable<decimal> _Сумма;
		
		private bool _DEL;
		
		private EntityRef<Работник> _Работник;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnработникIDChanging(int value);
    partial void OnработникIDChanged();
    partial void OnДатаChanging(System.DateTime value);
    partial void OnДатаChanged();
    partial void OnСуммаChanging(System.Nullable<decimal> value);
    partial void OnСуммаChanged();
    partial void OnDELChanging(bool value);
    partial void OnDELChanged();
    #endregion
		
		public Удержания()
		{
			this._Работник = default(EntityRef<Работник>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_работникID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int работникID
		{
			get
			{
				return this._работникID;
			}
			set
			{
				if ((this._работникID != value))
				{
					if (this._Работник.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnработникIDChanging(value);
					this.SendPropertyChanging();
					this._работникID = value;
					this.SendPropertyChanged("работникID");
					this.OnработникIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Дата", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime Дата
		{
			get
			{
				return this._Дата;
			}
			set
			{
				if ((this._Дата != value))
				{
					this.OnДатаChanging(value);
					this.SendPropertyChanging();
					this._Дата = value;
					this.SendPropertyChanged("Дата");
					this.OnДатаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Сумма", DbType="Money")]
		public System.Nullable<decimal> Сумма
		{
			get
			{
				return this._Сумма;
			}
			set
			{
				if ((this._Сумма != value))
				{
					this.OnСуммаChanging(value);
					this.SendPropertyChanging();
					this._Сумма = value;
					this.SendPropertyChanged("Сумма");
					this.OnСуммаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEL", DbType="Bit NOT NULL")]
		public bool DEL
		{
			get
			{
				return this._DEL;
			}
			set
			{
				if ((this._DEL != value))
				{
					this.OnDELChanging(value);
					this.SendPropertyChanging();
					this._DEL = value;
					this.SendPropertyChanged("DEL");
					this.OnDELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Работник_Удержания", Storage="_Работник", ThisKey="работникID", OtherKey="работникID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Работник Работник
		{
			get
			{
				return this._Работник.Entity;
			}
			set
			{
				Работник previousValue = this._Работник.Entity;
				if (((previousValue != value) 
							|| (this._Работник.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Работник.Entity = null;
						previousValue.Удержанияs.Remove(this);
					}
					this._Работник.Entity = value;
					if ((value != null))
					{
						value.Удержанияs.Add(this);
						this._работникID = value.работникID;
					}
					else
					{
						this._работникID = default(int);
					}
					this.SendPropertyChanged("Работник");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Работник")]
	public partial class Работник : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Номер_договора;
		
		private string _ФИО;
		
		private System.Nullable<System.DateTime> _Дата_договора;
		
		private string _Условия_договора;
		
		private int _работникID;
		
		private string _Инвалидность;
		
		private System.Nullable<System.DateTime> _Дата_выплаты_вознаграждения;
		
		private System.Nullable<short> _Тариф_пенс_взносов;
		
		private bool _DEL;
		
		private string _Документы_вычеты;
		
		private System.Nullable<short> _Тариф_страх_взносов;
		
		private EntitySet<Удержания> _Удержанияs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnНомер_договораChanging(string value);
    partial void OnНомер_договораChanged();
    partial void OnФИОChanging(string value);
    partial void OnФИОChanged();
    partial void OnДата_договораChanging(System.Nullable<System.DateTime> value);
    partial void OnДата_договораChanged();
    partial void OnУсловия_договораChanging(string value);
    partial void OnУсловия_договораChanged();
    partial void OnработникIDChanging(int value);
    partial void OnработникIDChanged();
    partial void OnИнвалидностьChanging(string value);
    partial void OnИнвалидностьChanged();
    partial void OnДата_выплаты_вознагражденияChanging(System.Nullable<System.DateTime> value);
    partial void OnДата_выплаты_вознагражденияChanged();
    partial void OnТариф_пенс_взносовChanging(System.Nullable<short> value);
    partial void OnТариф_пенс_взносовChanged();
    partial void OnDELChanging(bool value);
    partial void OnDELChanged();
    partial void OnДокументы_вычетыChanging(string value);
    partial void OnДокументы_вычетыChanged();
    partial void OnТариф_страх_взносовChanging(System.Nullable<short> value);
    partial void OnТариф_страх_взносовChanged();
    #endregion
		
		public Работник()
		{
			this._Удержанияs = new EntitySet<Удержания>(new Action<Удержания>(this.attach_Удержанияs), new Action<Удержания>(this.detach_Удержанияs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Номер_договора", DbType="VarChar(30)")]
		public string Номер_договора
		{
			get
			{
				return this._Номер_договора;
			}
			set
			{
				if ((this._Номер_договора != value))
				{
					this.OnНомер_договораChanging(value);
					this.SendPropertyChanging();
					this._Номер_договора = value;
					this.SendPropertyChanged("Номер_договора");
					this.OnНомер_договораChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ФИО", DbType="VarChar(150)")]
		public string ФИО
		{
			get
			{
				return this._ФИО;
			}
			set
			{
				if ((this._ФИО != value))
				{
					this.OnФИОChanging(value);
					this.SendPropertyChanging();
					this._ФИО = value;
					this.SendPropertyChanged("ФИО");
					this.OnФИОChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Дата_договора", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_договора
		{
			get
			{
				return this._Дата_договора;
			}
			set
			{
				if ((this._Дата_договора != value))
				{
					this.OnДата_договораChanging(value);
					this.SendPropertyChanging();
					this._Дата_договора = value;
					this.SendPropertyChanged("Дата_договора");
					this.OnДата_договораChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Условия_договора", DbType="VarChar(600)")]
		public string Условия_договора
		{
			get
			{
				return this._Условия_договора;
			}
			set
			{
				if ((this._Условия_договора != value))
				{
					this.OnУсловия_договораChanging(value);
					this.SendPropertyChanging();
					this._Условия_договора = value;
					this.SendPropertyChanged("Условия_договора");
					this.OnУсловия_договораChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_работникID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int работникID
		{
			get
			{
				return this._работникID;
			}
			set
			{
				if ((this._работникID != value))
				{
					this.OnработникIDChanging(value);
					this.SendPropertyChanging();
					this._работникID = value;
					this.SendPropertyChanged("работникID");
					this.OnработникIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Инвалидность", DbType="VarChar(200)")]
		public string Инвалидность
		{
			get
			{
				return this._Инвалидность;
			}
			set
			{
				if ((this._Инвалидность != value))
				{
					this.OnИнвалидностьChanging(value);
					this.SendPropertyChanging();
					this._Инвалидность = value;
					this.SendPropertyChanged("Инвалидность");
					this.OnИнвалидностьChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Дата_выплаты_вознаграждения", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_выплаты_вознаграждения
		{
			get
			{
				return this._Дата_выплаты_вознаграждения;
			}
			set
			{
				if ((this._Дата_выплаты_вознаграждения != value))
				{
					this.OnДата_выплаты_вознагражденияChanging(value);
					this.SendPropertyChanging();
					this._Дата_выплаты_вознаграждения = value;
					this.SendPropertyChanged("Дата_выплаты_вознаграждения");
					this.OnДата_выплаты_вознагражденияChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Тариф_пенс_взносов", DbType="SmallInt")]
		public System.Nullable<short> Тариф_пенс_взносов
		{
			get
			{
				return this._Тариф_пенс_взносов;
			}
			set
			{
				if ((this._Тариф_пенс_взносов != value))
				{
					this.OnТариф_пенс_взносовChanging(value);
					this.SendPropertyChanging();
					this._Тариф_пенс_взносов = value;
					this.SendPropertyChanged("Тариф_пенс_взносов");
					this.OnТариф_пенс_взносовChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEL", DbType="Bit NOT NULL")]
		public bool DEL
		{
			get
			{
				return this._DEL;
			}
			set
			{
				if ((this._DEL != value))
				{
					this.OnDELChanging(value);
					this.SendPropertyChanging();
					this._DEL = value;
					this.SendPropertyChanged("DEL");
					this.OnDELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Документы_вычеты", DbType="VarChar(200)")]
		public string Документы_вычеты
		{
			get
			{
				return this._Документы_вычеты;
			}
			set
			{
				if ((this._Документы_вычеты != value))
				{
					this.OnДокументы_вычетыChanging(value);
					this.SendPropertyChanging();
					this._Документы_вычеты = value;
					this.SendPropertyChanged("Документы_вычеты");
					this.OnДокументы_вычетыChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Тариф_страх_взносов", DbType="SmallInt")]
		public System.Nullable<short> Тариф_страх_взносов
		{
			get
			{
				return this._Тариф_страх_взносов;
			}
			set
			{
				if ((this._Тариф_страх_взносов != value))
				{
					this.OnТариф_страх_взносовChanging(value);
					this.SendPropertyChanging();
					this._Тариф_страх_взносов = value;
					this.SendPropertyChanged("Тариф_страх_взносов");
					this.OnТариф_страх_взносовChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Работник_Удержания", Storage="_Удержанияs", ThisKey="работникID", OtherKey="работникID")]
		public EntitySet<Удержания> Удержанияs
		{
			get
			{
				return this._Удержанияs;
			}
			set
			{
				this._Удержанияs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Удержанияs(Удержания entity)
		{
			this.SendPropertyChanging();
			entity.Работник = this;
		}
		
		private void detach_Удержанияs(Удержания entity)
		{
			this.SendPropertyChanging();
			entity.Работник = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_Зарплаты")]
	public partial class view_Зарплаты
	{
		
		private string _ФИО;
		
		private System.Nullable<decimal> _Зарплата_сумма;
		
		private System.Nullable<System.DateTime> _Начало_периода;
		
		private System.Nullable<System.DateTime> _Конец_периода;
		
		private int _работникID;
		
		public view_Зарплаты()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ФИО", DbType="VarChar(150)")]
		public string ФИО
		{
			get
			{
				return this._ФИО;
			}
			set
			{
				if ((this._ФИО != value))
				{
					this._ФИО = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Зарплата сумма]", Storage="_Зарплата_сумма", DbType="Money")]
		public System.Nullable<decimal> Зарплата_сумма
		{
			get
			{
				return this._Зарплата_сумма;
			}
			set
			{
				if ((this._Зарплата_сумма != value))
				{
					this._Зарплата_сумма = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Начало периода]", Storage="_Начало_периода", DbType="DateTime")]
		public System.Nullable<System.DateTime> Начало_периода
		{
			get
			{
				return this._Начало_периода;
			}
			set
			{
				if ((this._Начало_периода != value))
				{
					this._Начало_периода = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Конец периода]", Storage="_Конец_периода", DbType="DateTime")]
		public System.Nullable<System.DateTime> Конец_периода
		{
			get
			{
				return this._Конец_периода;
			}
			set
			{
				if ((this._Конец_периода != value))
				{
					this._Конец_периода = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_работникID", DbType="Int NOT NULL")]
		public int работникID
		{
			get
			{
				return this._работникID;
			}
			set
			{
				if ((this._работникID != value))
				{
					this._работникID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_ПодоходныйНалогПеречисл")]
	public partial class view_ПодоходныйНалогПеречисл
	{
		
		private int _работникID;
		
		private System.Nullable<bool> _DEL;
		
		private System.Nullable<bool> _Expr1;
		
		private System.DateTime _Месяц;
		
		private System.Nullable<decimal> _Начислено;
		
		private System.Nullable<decimal> _Перечислено;
		
		private System.Nullable<System.DateTime> _Дата;
		
		private string _Номер_платежной_инструкции;
		
		private System.Nullable<int> _ID_платежный_док;
		
		public view_ПодоходныйНалогПеречисл()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_работникID", DbType="Int NOT NULL")]
		public int работникID
		{
			get
			{
				return this._работникID;
			}
			set
			{
				if ((this._работникID != value))
				{
					this._работникID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEL", DbType="Bit")]
		public System.Nullable<bool> DEL
		{
			get
			{
				return this._DEL;
			}
			set
			{
				if ((this._DEL != value))
				{
					this._DEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expr1", DbType="Bit")]
		public System.Nullable<bool> Expr1
		{
			get
			{
				return this._Expr1;
			}
			set
			{
				if ((this._Expr1 != value))
				{
					this._Expr1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Месяц", DbType="DateTime NOT NULL")]
		public System.DateTime Месяц
		{
			get
			{
				return this._Месяц;
			}
			set
			{
				if ((this._Месяц != value))
				{
					this._Месяц = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Начислено", DbType="Money")]
		public System.Nullable<decimal> Начислено
		{
			get
			{
				return this._Начислено;
			}
			set
			{
				if ((this._Начислено != value))
				{
					this._Начислено = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Перечислено", DbType="Money")]
		public System.Nullable<decimal> Перечислено
		{
			get
			{
				return this._Перечислено;
			}
			set
			{
				if ((this._Перечислено != value))
				{
					this._Перечислено = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Дата", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата
		{
			get
			{
				return this._Дата;
			}
			set
			{
				if ((this._Дата != value))
				{
					this._Дата = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Номер платежной инструкции]", Storage="_Номер_платежной_инструкции", DbType="VarChar(20)")]
		public string Номер_платежной_инструкции
		{
			get
			{
				return this._Номер_платежной_инструкции;
			}
			set
			{
				if ((this._Номер_платежной_инструкции != value))
				{
					this._Номер_платежной_инструкции = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_платежный_док", DbType="Int")]
		public System.Nullable<int> ID_платежный_док
		{
			get
			{
				return this._ID_платежный_док;
			}
			set
			{
				if ((this._ID_платежный_док != value))
				{
					this._ID_платежный_док = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_Дивиденты")]
	public partial class view_Дивиденты
	{
		
		private int _ID;
		
		private System.Nullable<int> _ID_платежный_док;
		
		private string _Наименование_организации;
		
		private System.Nullable<System.DateTime> _Дата_начисления;
		
		private System.Nullable<decimal> _Сумма;
		
		private System.Nullable<decimal> _Налоговая_база;
		
		private System.Nullable<int> _Ставка_налога;
		
		private System.Nullable<float> _Сумма_налога;
		
		private System.Nullable<System.DateTime> _Дата_плат_инстр;
		
		private string _Номер_плат_инстр;
		
		private System.Nullable<decimal> _Перечислено_налога;
		
		private bool _DEL;
		
		public view_Дивиденты()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_платежный_док", DbType="Int")]
		public System.Nullable<int> ID_платежный_док
		{
			get
			{
				return this._ID_платежный_док;
			}
			set
			{
				if ((this._ID_платежный_док != value))
				{
					this._ID_платежный_док = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Наименование организации]", Storage="_Наименование_организации", DbType="VarChar(150)")]
		public string Наименование_организации
		{
			get
			{
				return this._Наименование_организации;
			}
			set
			{
				if ((this._Наименование_организации != value))
				{
					this._Наименование_организации = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата начисления]", Storage="_Дата_начисления", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_начисления
		{
			get
			{
				return this._Дата_начисления;
			}
			set
			{
				if ((this._Дата_начисления != value))
				{
					this._Дата_начисления = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Сумма", DbType="Money")]
		public System.Nullable<decimal> Сумма
		{
			get
			{
				return this._Сумма;
			}
			set
			{
				if ((this._Сумма != value))
				{
					this._Сумма = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Налоговая база]", Storage="_Налоговая_база", DbType="Money")]
		public System.Nullable<decimal> Налоговая_база
		{
			get
			{
				return this._Налоговая_база;
			}
			set
			{
				if ((this._Налоговая_база != value))
				{
					this._Налоговая_база = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ставка налога]", Storage="_Ставка_налога", DbType="Int")]
		public System.Nullable<int> Ставка_налога
		{
			get
			{
				return this._Ставка_налога;
			}
			set
			{
				if ((this._Ставка_налога != value))
				{
					this._Ставка_налога = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Сумма налога]", Storage="_Сумма_налога", DbType="Real")]
		public System.Nullable<float> Сумма_налога
		{
			get
			{
				return this._Сумма_налога;
			}
			set
			{
				if ((this._Сумма_налога != value))
				{
					this._Сумма_налога = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата плат инстр]", Storage="_Дата_плат_инстр", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_плат_инстр
		{
			get
			{
				return this._Дата_плат_инстр;
			}
			set
			{
				if ((this._Дата_плат_инстр != value))
				{
					this._Дата_плат_инстр = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Номер плат инстр]", Storage="_Номер_плат_инстр", DbType="VarChar(20)")]
		public string Номер_плат_инстр
		{
			get
			{
				return this._Номер_плат_инстр;
			}
			set
			{
				if ((this._Номер_плат_инстр != value))
				{
					this._Номер_плат_инстр = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Перечислено налога]", Storage="_Перечислено_налога", DbType="Money")]
		public System.Nullable<decimal> Перечислено_налога
		{
			get
			{
				return this._Перечислено_налога;
			}
			set
			{
				if ((this._Перечислено_налога != value))
				{
					this._Перечислено_налога = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEL", DbType="Bit NOT NULL")]
		public bool DEL
		{
			get
			{
				return this._DEL;
			}
			set
			{
				if ((this._DEL != value))
				{
					this._DEL = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_НалоговыйАгент")]
	public partial class view_НалоговыйАгент
	{
		
		private int _ID;
		
		private bool _DEL;
		
		private System.Nullable<int> _ID_платежный_док;
		
		private string _Наименование_организации;
		
		private string _Страна;
		
		private string _Вид_дохода;
		
		private System.Nullable<System.DateTime> _Дата_начисления_платежа;
		
		private System.Nullable<decimal> _Сумма_платежа;
		
		private System.Nullable<decimal> _Сумма_затрат_для_исчисления_налога;
		
		private System.Nullable<decimal> _Сумма_дохода_осв_от_налога_по_зак_РБ;
		
		private System.Nullable<decimal> _по_международному_договору;
		
		private System.Nullable<decimal> _облагаемый_доход;
		
		private System.Nullable<short> _Ставка_налога_по_зак_РБ;
		
		private System.Nullable<int> _ставка_по_международному_договору;
		
		private System.Nullable<float> _Подлежит_уплате;
		
		private System.Nullable<decimal> _Перечислено;
		
		private System.Nullable<System.DateTime> _Дата_плат_инстр;
		
		private string _Номер_плат_инстр;
		
		public view_НалоговыйАгент()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEL", DbType="Bit NOT NULL")]
		public bool DEL
		{
			get
			{
				return this._DEL;
			}
			set
			{
				if ((this._DEL != value))
				{
					this._DEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_платежный_док", DbType="Int")]
		public System.Nullable<int> ID_платежный_док
		{
			get
			{
				return this._ID_платежный_док;
			}
			set
			{
				if ((this._ID_платежный_док != value))
				{
					this._ID_платежный_док = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Наименование организации]", Storage="_Наименование_организации", DbType="VarChar(100)")]
		public string Наименование_организации
		{
			get
			{
				return this._Наименование_организации;
			}
			set
			{
				if ((this._Наименование_организации != value))
				{
					this._Наименование_организации = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Страна", DbType="VarChar(100)")]
		public string Страна
		{
			get
			{
				return this._Страна;
			}
			set
			{
				if ((this._Страна != value))
				{
					this._Страна = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Вид дохода]", Storage="_Вид_дохода", DbType="VarChar(150)")]
		public string Вид_дохода
		{
			get
			{
				return this._Вид_дохода;
			}
			set
			{
				if ((this._Вид_дохода != value))
				{
					this._Вид_дохода = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата начисления платежа]", Storage="_Дата_начисления_платежа", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_начисления_платежа
		{
			get
			{
				return this._Дата_начисления_платежа;
			}
			set
			{
				if ((this._Дата_начисления_платежа != value))
				{
					this._Дата_начисления_платежа = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Сумма платежа]", Storage="_Сумма_платежа", DbType="Money")]
		public System.Nullable<decimal> Сумма_платежа
		{
			get
			{
				return this._Сумма_платежа;
			}
			set
			{
				if ((this._Сумма_платежа != value))
				{
					this._Сумма_платежа = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Сумма затрат для исчисления налога]", Storage="_Сумма_затрат_для_исчисления_налога", DbType="Money")]
		public System.Nullable<decimal> Сумма_затрат_для_исчисления_налога
		{
			get
			{
				return this._Сумма_затрат_для_исчисления_налога;
			}
			set
			{
				if ((this._Сумма_затрат_для_исчисления_налога != value))
				{
					this._Сумма_затрат_для_исчисления_налога = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Сумма дохода осв от налога по зак РБ]", Storage="_Сумма_дохода_осв_от_налога_по_зак_РБ", DbType="Money")]
		public System.Nullable<decimal> Сумма_дохода_осв_от_налога_по_зак_РБ
		{
			get
			{
				return this._Сумма_дохода_осв_от_налога_по_зак_РБ;
			}
			set
			{
				if ((this._Сумма_дохода_осв_от_налога_по_зак_РБ != value))
				{
					this._Сумма_дохода_осв_от_налога_по_зак_РБ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[по международному договору]", Storage="_по_международному_договору", DbType="Money")]
		public System.Nullable<decimal> по_международному_договору
		{
			get
			{
				return this._по_международному_договору;
			}
			set
			{
				if ((this._по_международному_договору != value))
				{
					this._по_международному_договору = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[облагаемый доход]", Storage="_облагаемый_доход", DbType="Money")]
		public System.Nullable<decimal> облагаемый_доход
		{
			get
			{
				return this._облагаемый_доход;
			}
			set
			{
				if ((this._облагаемый_доход != value))
				{
					this._облагаемый_доход = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ставка налога по зак РБ]", Storage="_Ставка_налога_по_зак_РБ", DbType="SmallInt")]
		public System.Nullable<short> Ставка_налога_по_зак_РБ
		{
			get
			{
				return this._Ставка_налога_по_зак_РБ;
			}
			set
			{
				if ((this._Ставка_налога_по_зак_РБ != value))
				{
					this._Ставка_налога_по_зак_РБ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ставка по международному договору]", Storage="_ставка_по_международному_договору", DbType="Int")]
		public System.Nullable<int> ставка_по_международному_договору
		{
			get
			{
				return this._ставка_по_международному_договору;
			}
			set
			{
				if ((this._ставка_по_международному_договору != value))
				{
					this._ставка_по_международному_договору = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Подлежит уплате]", Storage="_Подлежит_уплате", DbType="Real")]
		public System.Nullable<float> Подлежит_уплате
		{
			get
			{
				return this._Подлежит_уплате;
			}
			set
			{
				if ((this._Подлежит_уплате != value))
				{
					this._Подлежит_уплате = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Перечислено", DbType="Money")]
		public System.Nullable<decimal> Перечислено
		{
			get
			{
				return this._Перечислено;
			}
			set
			{
				if ((this._Перечислено != value))
				{
					this._Перечислено = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата плат инстр]", Storage="_Дата_плат_инстр", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_плат_инстр
		{
			get
			{
				return this._Дата_плат_инстр;
			}
			set
			{
				if ((this._Дата_плат_инстр != value))
				{
					this._Дата_плат_инстр = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Номер плат инстр]", Storage="_Номер_плат_инстр", DbType="VarChar(20)")]
		public string Номер_плат_инстр
		{
			get
			{
				return this._Номер_плат_инстр;
			}
			set
			{
				if ((this._Номер_плат_инстр != value))
				{
					this._Номер_плат_инстр = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Производственный_кооператив")]
	public partial class Производственный_кооператив : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _ФИО;
		
		private System.Nullable<decimal> _Размер_пая;
		
		private System.Nullable<decimal> _Размер_паевых_взносов;
		
		private System.Nullable<decimal> _Выплачена_стоимость_пая;
		
		private System.Nullable<decimal> _Выдано_иное_имущество;
		
		private System.Nullable<decimal> _Иные_выплаты_при_выходе_из_кооператива;
		
		private bool _DEL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnФИОChanging(string value);
    partial void OnФИОChanged();
    partial void OnРазмер_паяChanging(System.Nullable<decimal> value);
    partial void OnРазмер_паяChanged();
    partial void OnРазмер_паевых_взносовChanging(System.Nullable<decimal> value);
    partial void OnРазмер_паевых_взносовChanged();
    partial void OnВыплачена_стоимость_паяChanging(System.Nullable<decimal> value);
    partial void OnВыплачена_стоимость_паяChanged();
    partial void OnВыдано_иное_имуществоChanging(System.Nullable<decimal> value);
    partial void OnВыдано_иное_имуществоChanged();
    partial void OnИные_выплаты_при_выходе_из_кооперативаChanging(System.Nullable<decimal> value);
    partial void OnИные_выплаты_при_выходе_из_кооперативаChanged();
    partial void OnDELChanging(bool value);
    partial void OnDELChanged();
    #endregion
		
		public Производственный_кооператив()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ФИО", DbType="VarChar(150)")]
		public string ФИО
		{
			get
			{
				return this._ФИО;
			}
			set
			{
				if ((this._ФИО != value))
				{
					this.OnФИОChanging(value);
					this.SendPropertyChanging();
					this._ФИО = value;
					this.SendPropertyChanged("ФИО");
					this.OnФИОChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Размер_пая", DbType="Money")]
		public System.Nullable<decimal> Размер_пая
		{
			get
			{
				return this._Размер_пая;
			}
			set
			{
				if ((this._Размер_пая != value))
				{
					this.OnРазмер_паяChanging(value);
					this.SendPropertyChanging();
					this._Размер_пая = value;
					this.SendPropertyChanged("Размер_пая");
					this.OnРазмер_паяChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Размер_паевых_взносов", DbType="Money")]
		public System.Nullable<decimal> Размер_паевых_взносов
		{
			get
			{
				return this._Размер_паевых_взносов;
			}
			set
			{
				if ((this._Размер_паевых_взносов != value))
				{
					this.OnРазмер_паевых_взносовChanging(value);
					this.SendPropertyChanging();
					this._Размер_паевых_взносов = value;
					this.SendPropertyChanged("Размер_паевых_взносов");
					this.OnРазмер_паевых_взносовChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Выплачена_стоимость_пая", DbType="Money")]
		public System.Nullable<decimal> Выплачена_стоимость_пая
		{
			get
			{
				return this._Выплачена_стоимость_пая;
			}
			set
			{
				if ((this._Выплачена_стоимость_пая != value))
				{
					this.OnВыплачена_стоимость_паяChanging(value);
					this.SendPropertyChanging();
					this._Выплачена_стоимость_пая = value;
					this.SendPropertyChanged("Выплачена_стоимость_пая");
					this.OnВыплачена_стоимость_паяChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Выдано_иное_имущество", DbType="Money")]
		public System.Nullable<decimal> Выдано_иное_имущество
		{
			get
			{
				return this._Выдано_иное_имущество;
			}
			set
			{
				if ((this._Выдано_иное_имущество != value))
				{
					this.OnВыдано_иное_имуществоChanging(value);
					this.SendPropertyChanging();
					this._Выдано_иное_имущество = value;
					this.SendPropertyChanged("Выдано_иное_имущество");
					this.OnВыдано_иное_имуществоChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Иные_выплаты_при_выходе_из_кооператива", DbType="Money")]
		public System.Nullable<decimal> Иные_выплаты_при_выходе_из_кооператива
		{
			get
			{
				return this._Иные_выплаты_при_выходе_из_кооператива;
			}
			set
			{
				if ((this._Иные_выплаты_при_выходе_из_кооператива != value))
				{
					this.OnИные_выплаты_при_выходе_из_кооперативаChanging(value);
					this.SendPropertyChanging();
					this._Иные_выплаты_при_выходе_из_кооператива = value;
					this.SendPropertyChanged("Иные_выплаты_при_выходе_из_кооператива");
					this.OnИные_выплаты_при_выходе_из_кооперативаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEL", DbType="Bit NOT NULL")]
		public bool DEL
		{
			get
			{
				return this._DEL;
			}
			set
			{
				if ((this._DEL != value))
				{
					this.OnDELChanging(value);
					this.SendPropertyChanging();
					this._DEL = value;
					this.SendPropertyChanged("DEL");
					this.OnDELChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_СтрахВзнос")]
	public partial class view_СтрахВзнос
	{
		
		private int _работникID;
		
		private string _ФИО;
		
		private System.DateTime _Дата;
		
		private System.Nullable<decimal> _Общая_сумма_выплат;
		
		private System.Nullable<decimal> _Сумма_на_которую_начисл_страх_взносы;
		
		private System.Nullable<decimal> _Сумма_начисл_страх_взносов_всего;
		
		private System.Nullable<decimal> _в_том_числе_1_процент;
		
		private System.Nullable<decimal> _Иные_платежи;
		
		private System.Nullable<decimal> _Перечислено_фондом_плательщику;
		
		private System.Nullable<decimal> _Сумма_начисленных_пособий;
		
		private System.Nullable<decimal> _Остаток_задолженности_за_пред_период;
		
		private System.Nullable<decimal> _Подлежит_уплате;
		
		private System.Nullable<decimal> _Перечислено_в_Фонд;
		
		private System.Nullable<System.DateTime> _Дата_плат_инстр;
		
		private string _Номер_плат_инстр;
		
		private System.Nullable<float> _Остаток_задолженности;
		
		private System.Nullable<int> _ID_платежный_док;
		
		private bool _DEL;
		
		private System.Nullable<byte> _За_месяц;
		
		private System.Nullable<short> _Количество_рабочих_дней;
		
		public view_СтрахВзнос()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_работникID", DbType="Int NOT NULL")]
		public int работникID
		{
			get
			{
				return this._работникID;
			}
			set
			{
				if ((this._работникID != value))
				{
					this._работникID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ФИО", DbType="VarChar(150)")]
		public string ФИО
		{
			get
			{
				return this._ФИО;
			}
			set
			{
				if ((this._ФИО != value))
				{
					this._ФИО = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Дата", DbType="DateTime NOT NULL")]
		public System.DateTime Дата
		{
			get
			{
				return this._Дата;
			}
			set
			{
				if ((this._Дата != value))
				{
					this._Дата = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Общая сумма выплат]", Storage="_Общая_сумма_выплат", DbType="Money")]
		public System.Nullable<decimal> Общая_сумма_выплат
		{
			get
			{
				return this._Общая_сумма_выплат;
			}
			set
			{
				if ((this._Общая_сумма_выплат != value))
				{
					this._Общая_сумма_выплат = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Сумма на которую начисл страх взносы]", Storage="_Сумма_на_которую_начисл_страх_взносы", DbType="Money")]
		public System.Nullable<decimal> Сумма_на_которую_начисл_страх_взносы
		{
			get
			{
				return this._Сумма_на_которую_начисл_страх_взносы;
			}
			set
			{
				if ((this._Сумма_на_которую_начисл_страх_взносы != value))
				{
					this._Сумма_на_которую_начисл_страх_взносы = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Сумма начисл страх взносов всего]", Storage="_Сумма_начисл_страх_взносов_всего", DbType="Money")]
		public System.Nullable<decimal> Сумма_начисл_страх_взносов_всего
		{
			get
			{
				return this._Сумма_начисл_страх_взносов_всего;
			}
			set
			{
				if ((this._Сумма_начисл_страх_взносов_всего != value))
				{
					this._Сумма_начисл_страх_взносов_всего = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[в том числе 1 процент]", Storage="_в_том_числе_1_процент", DbType="Money")]
		public System.Nullable<decimal> в_том_числе_1_процент
		{
			get
			{
				return this._в_том_числе_1_процент;
			}
			set
			{
				if ((this._в_том_числе_1_процент != value))
				{
					this._в_том_числе_1_процент = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Иные платежи]", Storage="_Иные_платежи", DbType="Money")]
		public System.Nullable<decimal> Иные_платежи
		{
			get
			{
				return this._Иные_платежи;
			}
			set
			{
				if ((this._Иные_платежи != value))
				{
					this._Иные_платежи = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Перечислено фондом плательщику]", Storage="_Перечислено_фондом_плательщику", DbType="Money")]
		public System.Nullable<decimal> Перечислено_фондом_плательщику
		{
			get
			{
				return this._Перечислено_фондом_плательщику;
			}
			set
			{
				if ((this._Перечислено_фондом_плательщику != value))
				{
					this._Перечислено_фондом_плательщику = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Сумма начисленных пособий]", Storage="_Сумма_начисленных_пособий", DbType="Money")]
		public System.Nullable<decimal> Сумма_начисленных_пособий
		{
			get
			{
				return this._Сумма_начисленных_пособий;
			}
			set
			{
				if ((this._Сумма_начисленных_пособий != value))
				{
					this._Сумма_начисленных_пособий = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Остаток задолженности за пред период]", Storage="_Остаток_задолженности_за_пред_период", DbType="Money")]
		public System.Nullable<decimal> Остаток_задолженности_за_пред_период
		{
			get
			{
				return this._Остаток_задолженности_за_пред_период;
			}
			set
			{
				if ((this._Остаток_задолженности_за_пред_период != value))
				{
					this._Остаток_задолженности_за_пред_период = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Подлежит уплате]", Storage="_Подлежит_уплате", DbType="Money")]
		public System.Nullable<decimal> Подлежит_уплате
		{
			get
			{
				return this._Подлежит_уплате;
			}
			set
			{
				if ((this._Подлежит_уплате != value))
				{
					this._Подлежит_уплате = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Перечислено в Фонд]", Storage="_Перечислено_в_Фонд", DbType="Money")]
		public System.Nullable<decimal> Перечислено_в_Фонд
		{
			get
			{
				return this._Перечислено_в_Фонд;
			}
			set
			{
				if ((this._Перечислено_в_Фонд != value))
				{
					this._Перечислено_в_Фонд = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата плат инстр]", Storage="_Дата_плат_инстр", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_плат_инстр
		{
			get
			{
				return this._Дата_плат_инстр;
			}
			set
			{
				if ((this._Дата_плат_инстр != value))
				{
					this._Дата_плат_инстр = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Номер плат инстр]", Storage="_Номер_плат_инстр", DbType="VarChar(20)")]
		public string Номер_плат_инстр
		{
			get
			{
				return this._Номер_плат_инстр;
			}
			set
			{
				if ((this._Номер_плат_инстр != value))
				{
					this._Номер_плат_инстр = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Остаток задолженности]", Storage="_Остаток_задолженности", DbType="Real")]
		public System.Nullable<float> Остаток_задолженности
		{
			get
			{
				return this._Остаток_задолженности;
			}
			set
			{
				if ((this._Остаток_задолженности != value))
				{
					this._Остаток_задолженности = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_платежный_док", DbType="Int")]
		public System.Nullable<int> ID_платежный_док
		{
			get
			{
				return this._ID_платежный_док;
			}
			set
			{
				if ((this._ID_платежный_док != value))
				{
					this._ID_платежный_док = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEL", DbType="Bit NOT NULL")]
		public bool DEL
		{
			get
			{
				return this._DEL;
			}
			set
			{
				if ((this._DEL != value))
				{
					this._DEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[За месяц]", Storage="_За_месяц", DbType="TinyInt")]
		public System.Nullable<byte> За_месяц
		{
			get
			{
				return this._За_месяц;
			}
			set
			{
				if ((this._За_месяц != value))
				{
					this._За_месяц = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Количество рабочих дней]", Storage="_Количество_рабочих_дней", DbType="SmallInt")]
		public System.Nullable<short> Количество_рабочих_дней
		{
			get
			{
				return this._Количество_рабочих_дней;
			}
			set
			{
				if ((this._Количество_рабочих_дней != value))
				{
					this._Количество_рабочих_дней = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_ПенсВзносы")]
	public partial class view_ПенсВзносы
	{
		
		private int _работникID;
		
		private string _ФИО;
		
		private System.DateTime _Дата;
		
		private System.Nullable<decimal> _Сумма_на_которую_начисл_пенс_взносы;
		
		private System.Nullable<decimal> _Сумма_начисленных_пенс_взносов;
		
		private System.Nullable<decimal> _Остаток_задолженности_за_пред_период;
		
		private System.Nullable<decimal> _Иные_платежи;
		
		private System.Nullable<decimal> _Подлежит_уплате;
		
		private System.Nullable<decimal> _Перечислено_в_Фонд;
		
		private System.Nullable<System.DateTime> _Дата_плат_инстр;
		
		private string _Номер_плат_инстр;
		
		private System.Nullable<int> _ID_платежный_док;
		
		private bool _DEL;
		
		public view_ПенсВзносы()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_работникID", DbType="Int NOT NULL")]
		public int работникID
		{
			get
			{
				return this._работникID;
			}
			set
			{
				if ((this._работникID != value))
				{
					this._работникID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ФИО", DbType="VarChar(150)")]
		public string ФИО
		{
			get
			{
				return this._ФИО;
			}
			set
			{
				if ((this._ФИО != value))
				{
					this._ФИО = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Дата", DbType="DateTime NOT NULL")]
		public System.DateTime Дата
		{
			get
			{
				return this._Дата;
			}
			set
			{
				if ((this._Дата != value))
				{
					this._Дата = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Сумма на которую начисл пенс взносы]", Storage="_Сумма_на_которую_начисл_пенс_взносы", DbType="Money")]
		public System.Nullable<decimal> Сумма_на_которую_начисл_пенс_взносы
		{
			get
			{
				return this._Сумма_на_которую_начисл_пенс_взносы;
			}
			set
			{
				if ((this._Сумма_на_которую_начисл_пенс_взносы != value))
				{
					this._Сумма_на_которую_начисл_пенс_взносы = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Сумма начисленных пенс взносов]", Storage="_Сумма_начисленных_пенс_взносов", DbType="Money")]
		public System.Nullable<decimal> Сумма_начисленных_пенс_взносов
		{
			get
			{
				return this._Сумма_начисленных_пенс_взносов;
			}
			set
			{
				if ((this._Сумма_начисленных_пенс_взносов != value))
				{
					this._Сумма_начисленных_пенс_взносов = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Остаток задолженности за пред период]", Storage="_Остаток_задолженности_за_пред_период", DbType="Money")]
		public System.Nullable<decimal> Остаток_задолженности_за_пред_период
		{
			get
			{
				return this._Остаток_задолженности_за_пред_период;
			}
			set
			{
				if ((this._Остаток_задолженности_за_пред_период != value))
				{
					this._Остаток_задолженности_за_пред_период = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Иные платежи]", Storage="_Иные_платежи", DbType="Money")]
		public System.Nullable<decimal> Иные_платежи
		{
			get
			{
				return this._Иные_платежи;
			}
			set
			{
				if ((this._Иные_платежи != value))
				{
					this._Иные_платежи = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Подлежит уплате]", Storage="_Подлежит_уплате", DbType="Money")]
		public System.Nullable<decimal> Подлежит_уплате
		{
			get
			{
				return this._Подлежит_уплате;
			}
			set
			{
				if ((this._Подлежит_уплате != value))
				{
					this._Подлежит_уплате = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Перечислено в Фонд]", Storage="_Перечислено_в_Фонд", DbType="Money")]
		public System.Nullable<decimal> Перечислено_в_Фонд
		{
			get
			{
				return this._Перечислено_в_Фонд;
			}
			set
			{
				if ((this._Перечислено_в_Фонд != value))
				{
					this._Перечислено_в_Фонд = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата плат инстр]", Storage="_Дата_плат_инстр", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_плат_инстр
		{
			get
			{
				return this._Дата_плат_инстр;
			}
			set
			{
				if ((this._Дата_плат_инстр != value))
				{
					this._Дата_плат_инстр = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Номер плат инстр]", Storage="_Номер_плат_инстр", DbType="VarChar(20)")]
		public string Номер_плат_инстр
		{
			get
			{
				return this._Номер_плат_инстр;
			}
			set
			{
				if ((this._Номер_плат_инстр != value))
				{
					this._Номер_плат_инстр = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_платежный_док", DbType="Int")]
		public System.Nullable<int> ID_платежный_док
		{
			get
			{
				return this._ID_платежный_док;
			}
			set
			{
				if ((this._ID_платежный_док != value))
				{
					this._ID_платежный_док = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEL", DbType="Bit NOT NULL")]
		public bool DEL
		{
			get
			{
				return this._DEL;
			}
			set
			{
				if ((this._DEL != value))
				{
					this._DEL = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
