<?xml version="1.0" encoding="utf-8"?><Database Name="KUDIR" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=D:\VirtualBox\BBD\SHARE\KUDIR.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="Reports.Properties.Settings" SettingsPropertyName="KUDIRConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Выручка" Member="Выручкаs">
    <Type Name="Выручка">
      <Column Name="Выручка_от_реализации" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Внереализационные_доходы" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Содержание_операции" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="Дата_записи" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DEL" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Док_выручка_Наим" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Док_выручка_Номер" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Док_выручка_Дата" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.view_Отгрузка" Member="view_Отгрузкаs">
    <Type Name="view_Отгрузка">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Дата отгрузки]" Member="Дата_отгрузки" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Лицо которому реализ товар]" Member="Лицо_которому_реализ_товар" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Наим док отгрузки]" Member="Наим_док_отгрузки" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="[Номер док отгрузки]" Member="Номер_док_отгрузки" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="[Дата док отгрузки]" Member="Дата_док_отгрузки" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Стоимость отгр товаров в бр]" Member="Стоимость_отгр_товаров_в_бр" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="[Наим валюты]" Member="Наим_валюты" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Стоимость в валюте]" Member="Стоимость_в_валюте" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="[Наим док оплаты]" Member="Наим_док_оплаты" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="[Номер док оплаты]" Member="Номер_док_оплаты" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="[Дата док оплаты]" Member="Дата_док_оплаты" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Сумма" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DEL" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Предоплачено" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[Дата оплаты]" Member="Дата_оплаты" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.view_Предоплата" Member="view_Предоплатаs">
    <Type Name="view_Предоплата">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Дата предоплаты]" Member="Дата_предоплаты" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Лицо которому реализ товар]" Member="Лицо_которому_реализ_товар" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Наим док оплаты]" Member="Наим_док_оплаты" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="[Номер док оплаты]" Member="Номер_док_оплаты" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="[Дата док оплаты]" Member="Дата_док_оплаты" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Сумма предоплаты]" Member="Сумма_предоплаты" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="[Наим валюты]" Member="Наим_валюты" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Сумма в валюте]" Member="Сумма_в_валюте" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="[Наим док отгрузки]" Member="Наим_док_отгрузки" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="[Номер док отгрузки]" Member="Номер_док_отгрузки" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="[Дата док отгрузки]" Member="Дата_док_отгрузки" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Предоплачено" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DEL" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Сумма" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="[Дата отгрузки]" Member="Дата_отгрузки" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Кредитор" Member="Кредиторs">
    <Type Name="Кредитор">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Название" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="Сумма_бр" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Номер_договора" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Предмет_договора" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Дата_договора" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Наим_валюты" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Сумма_в_валюте" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DEL" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Док_задолж_Наим" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Док_задолж_Номер" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Док_задолж_Дата" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.view_Выплаты" Member="view_Выплатыs">
    <Type Name="view_Выплаты">
      <Column Name="Код_выплаты" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="работникID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DEL_Выплаты" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Сумма" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Причина" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="[Начало периода]" Member="Начало_периода" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Конец периода]" Member="Конец_периода" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Начисляются страх взносы]" Member="Начисляются_страх_взносы" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[Начисляются пенс взносы]" Member="Начисляются_пенс_взносы" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DEL_ВыплатыРаботнику" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.view_Вычет" Member="view_Вычетs">
    <Type Name="view_Вычет">
      <Column Name="Код_вычета" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="работникID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DEL_вычет" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Сумма" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="[Тип вычета]" Member="Тип_вычета" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="[Начало периода]" Member="Начало_периода" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Конец периода]" Member="Конец_периода" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DEL_вычетРаботника" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Удержания" Member="Удержанияs">
    <Type Name="Удержания">
      <Column Name="работникID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Дата" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Сумма" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DEL" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Работник_Удержания" Member="Работник" ThisKey="работникID" OtherKey="работникID" Type="Работник" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Работник" Member="Работникs">
    <Type Name="Работник">
      <Column Name="Номер_договора" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ФИО" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Дата_договора" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Условия_договора" Type="System.String" DbType="VarChar(600)" CanBeNull="true" />
      <Column Name="работникID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Инвалидность" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Дата_выплаты_вознаграждения" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Тариф_пенс_взносов" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DEL" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Документы_вычеты" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Тариф_страх_взносов" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="Работник_Удержания" Member="Удержанияs" ThisKey="работникID" OtherKey="работникID" Type="Удержания" />
    </Type>
  </Table>
  <Table Name="dbo.view_Зарплаты" Member="view_Зарплатыs">
    <Type Name="view_Зарплаты">
      <Column Name="ФИО" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="[Зарплата сумма]" Member="Зарплата_сумма" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="[Начало периода]" Member="Начало_периода" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Конец периода]" Member="Конец_периода" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="работникID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.СуммыВычетов" Method="СуммыВычетов">
    <Parameter Name="РаботникID" Parameter="работникID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Дата" Parameter="дата" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Стандартные" Parameter="стандартные" Type="System.Decimal" DbType="Money" Direction="InOut" />
    <Parameter Name="Социальные" Parameter="социальные" Type="System.Decimal" DbType="Money" Direction="InOut" />
    <Parameter Name="Имущественные" Parameter="имущественные" Type="System.Decimal" DbType="Money" Direction="InOut" />
    <Parameter Name="Профессиональные" Parameter="профессиональные" Type="System.Decimal" DbType="Money" Direction="InOut" />
    <Parameter Name="ОсвобождаемыеДоходы" Parameter="освобождаемыеДоходы" Type="System.Decimal" DbType="Money" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>