#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KUDIR")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertВыручка(Выручка instance);
    partial void UpdateВыручка(Выручка instance);
    partial void DeleteВыручка(Выручка instance);
    partial void InsertКредитор(Кредитор instance);
    partial void UpdateКредитор(Кредитор instance);
    partial void DeleteКредитор(Кредитор instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::Reports.Properties.Settings.Default.KUDIRConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Выручка> Выручкаs
		{
			get
			{
				return this.GetTable<Выручка>();
			}
		}
		
		public System.Data.Linq.Table<view_Отгрузка> view_Отгрузкаs
		{
			get
			{
				return this.GetTable<view_Отгрузка>();
			}
		}
		
		public System.Data.Linq.Table<view_Предоплата> view_Предоплатаs
		{
			get
			{
				return this.GetTable<view_Предоплата>();
			}
		}
		
		public System.Data.Linq.Table<Кредитор> Кредиторs
		{
			get
			{
				return this.GetTable<Кредитор>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Выручка")]
	public partial class Выручка : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<decimal> _Выручка_от_реализации;
		
		private System.Nullable<decimal> _Внереализационные_доходы;
		
		private string _Содержание_операции;
		
		private System.Nullable<System.DateTime> _Дата_записи;
		
		private int _ID;
		
		private bool _DEL;
		
		private string _Док_выручка_Наим;
		
		private string _Док_выручка_Номер;
		
		private System.Nullable<System.DateTime> _Док_выручка_Дата;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnВыручка_от_реализацииChanging(System.Nullable<decimal> value);
    partial void OnВыручка_от_реализацииChanged();
    partial void OnВнереализационные_доходыChanging(System.Nullable<decimal> value);
    partial void OnВнереализационные_доходыChanged();
    partial void OnСодержание_операцииChanging(string value);
    partial void OnСодержание_операцииChanged();
    partial void OnДата_записиChanging(System.Nullable<System.DateTime> value);
    partial void OnДата_записиChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDELChanging(bool value);
    partial void OnDELChanged();
    partial void OnДок_выручка_НаимChanging(string value);
    partial void OnДок_выручка_НаимChanged();
    partial void OnДок_выручка_НомерChanging(string value);
    partial void OnДок_выручка_НомерChanged();
    partial void OnДок_выручка_ДатаChanging(System.Nullable<System.DateTime> value);
    partial void OnДок_выручка_ДатаChanged();
    #endregion
		
		public Выручка()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Выручка_от_реализации", DbType="Money")]
		public System.Nullable<decimal> Выручка_от_реализации
		{
			get
			{
				return this._Выручка_от_реализации;
			}
			set
			{
				if ((this._Выручка_от_реализации != value))
				{
					this.OnВыручка_от_реализацииChanging(value);
					this.SendPropertyChanging();
					this._Выручка_от_реализации = value;
					this.SendPropertyChanged("Выручка_от_реализации");
					this.OnВыручка_от_реализацииChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Внереализационные_доходы", DbType="Money")]
		public System.Nullable<decimal> Внереализационные_доходы
		{
			get
			{
				return this._Внереализационные_доходы;
			}
			set
			{
				if ((this._Внереализационные_доходы != value))
				{
					this.OnВнереализационные_доходыChanging(value);
					this.SendPropertyChanging();
					this._Внереализационные_доходы = value;
					this.SendPropertyChanged("Внереализационные_доходы");
					this.OnВнереализационные_доходыChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Содержание_операции", DbType="VarChar(80)")]
		public string Содержание_операции
		{
			get
			{
				return this._Содержание_операции;
			}
			set
			{
				if ((this._Содержание_операции != value))
				{
					this.OnСодержание_операцииChanging(value);
					this.SendPropertyChanging();
					this._Содержание_операции = value;
					this.SendPropertyChanged("Содержание_операции");
					this.OnСодержание_операцииChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Дата_записи", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_записи
		{
			get
			{
				return this._Дата_записи;
			}
			set
			{
				if ((this._Дата_записи != value))
				{
					this.OnДата_записиChanging(value);
					this.SendPropertyChanging();
					this._Дата_записи = value;
					this.SendPropertyChanged("Дата_записи");
					this.OnДата_записиChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEL", DbType="Bit NOT NULL")]
		public bool DEL
		{
			get
			{
				return this._DEL;
			}
			set
			{
				if ((this._DEL != value))
				{
					this.OnDELChanging(value);
					this.SendPropertyChanging();
					this._DEL = value;
					this.SendPropertyChanged("DEL");
					this.OnDELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Док_выручка_Наим", DbType="VarChar(100)")]
		public string Док_выручка_Наим
		{
			get
			{
				return this._Док_выручка_Наим;
			}
			set
			{
				if ((this._Док_выручка_Наим != value))
				{
					this.OnДок_выручка_НаимChanging(value);
					this.SendPropertyChanging();
					this._Док_выручка_Наим = value;
					this.SendPropertyChanged("Док_выручка_Наим");
					this.OnДок_выручка_НаимChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Док_выручка_Номер", DbType="VarChar(30)")]
		public string Док_выручка_Номер
		{
			get
			{
				return this._Док_выручка_Номер;
			}
			set
			{
				if ((this._Док_выручка_Номер != value))
				{
					this.OnДок_выручка_НомерChanging(value);
					this.SendPropertyChanging();
					this._Док_выручка_Номер = value;
					this.SendPropertyChanged("Док_выручка_Номер");
					this.OnДок_выручка_НомерChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Док_выручка_Дата", DbType="DateTime")]
		public System.Nullable<System.DateTime> Док_выручка_Дата
		{
			get
			{
				return this._Док_выручка_Дата;
			}
			set
			{
				if ((this._Док_выручка_Дата != value))
				{
					this.OnДок_выручка_ДатаChanging(value);
					this.SendPropertyChanging();
					this._Док_выручка_Дата = value;
					this.SendPropertyChanged("Док_выручка_Дата");
					this.OnДок_выручка_ДатаChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_Отгрузка")]
	public partial class view_Отгрузка
	{
		
		private int _ID;
		
		private System.Nullable<System.DateTime> _Дата_отгрузки;
		
		private string _Лицо_которому_реализ_товар;
		
		private string _Наим_док_отгрузки;
		
		private string _Номер_док_отгрузки;
		
		private System.Nullable<System.DateTime> _Дата_док_отгрузки;
		
		private System.Nullable<decimal> _Стоимость_отгр_товаров_в_бр;
		
		private string _Наим_валюты;
		
		private System.Nullable<decimal> _Стоимость_в_валюте;
		
		private string _Наим_док_оплаты;
		
		private string _Номер_док_оплаты;
		
		private System.Nullable<System.DateTime> _Дата_док_оплаты;
		
		private System.Nullable<decimal> _Сумма;
		
		private bool _DEL;
		
		private System.Nullable<bool> _Предоплачено;
		
		private System.Nullable<System.DateTime> _Дата_оплаты;
		
		public view_Отгрузка()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата отгрузки]", Storage="_Дата_отгрузки", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_отгрузки
		{
			get
			{
				return this._Дата_отгрузки;
			}
			set
			{
				if ((this._Дата_отгрузки != value))
				{
					this._Дата_отгрузки = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Лицо которому реализ товар]", Storage="_Лицо_которому_реализ_товар", DbType="VarChar(50)")]
		public string Лицо_которому_реализ_товар
		{
			get
			{
				return this._Лицо_которому_реализ_товар;
			}
			set
			{
				if ((this._Лицо_которому_реализ_товар != value))
				{
					this._Лицо_которому_реализ_товар = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Наим док отгрузки]", Storage="_Наим_док_отгрузки", DbType="VarChar(100)")]
		public string Наим_док_отгрузки
		{
			get
			{
				return this._Наим_док_отгрузки;
			}
			set
			{
				if ((this._Наим_док_отгрузки != value))
				{
					this._Наим_док_отгрузки = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Номер док отгрузки]", Storage="_Номер_док_отгрузки", DbType="VarChar(30)")]
		public string Номер_док_отгрузки
		{
			get
			{
				return this._Номер_док_отгрузки;
			}
			set
			{
				if ((this._Номер_док_отгрузки != value))
				{
					this._Номер_док_отгрузки = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата док отгрузки]", Storage="_Дата_док_отгрузки", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_док_отгрузки
		{
			get
			{
				return this._Дата_док_отгрузки;
			}
			set
			{
				if ((this._Дата_док_отгрузки != value))
				{
					this._Дата_док_отгрузки = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Стоимость отгр товаров в бр]", Storage="_Стоимость_отгр_товаров_в_бр", DbType="Money")]
		public System.Nullable<decimal> Стоимость_отгр_товаров_в_бр
		{
			get
			{
				return this._Стоимость_отгр_товаров_в_бр;
			}
			set
			{
				if ((this._Стоимость_отгр_товаров_в_бр != value))
				{
					this._Стоимость_отгр_товаров_в_бр = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Наим валюты]", Storage="_Наим_валюты", DbType="VarChar(50)")]
		public string Наим_валюты
		{
			get
			{
				return this._Наим_валюты;
			}
			set
			{
				if ((this._Наим_валюты != value))
				{
					this._Наим_валюты = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Стоимость в валюте]", Storage="_Стоимость_в_валюте", DbType="Money")]
		public System.Nullable<decimal> Стоимость_в_валюте
		{
			get
			{
				return this._Стоимость_в_валюте;
			}
			set
			{
				if ((this._Стоимость_в_валюте != value))
				{
					this._Стоимость_в_валюте = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Наим док оплаты]", Storage="_Наим_док_оплаты", DbType="VarChar(100)")]
		public string Наим_док_оплаты
		{
			get
			{
				return this._Наим_док_оплаты;
			}
			set
			{
				if ((this._Наим_док_оплаты != value))
				{
					this._Наим_док_оплаты = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Номер док оплаты]", Storage="_Номер_док_оплаты", DbType="VarChar(30)")]
		public string Номер_док_оплаты
		{
			get
			{
				return this._Номер_док_оплаты;
			}
			set
			{
				if ((this._Номер_док_оплаты != value))
				{
					this._Номер_док_оплаты = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата док оплаты]", Storage="_Дата_док_оплаты", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_док_оплаты
		{
			get
			{
				return this._Дата_док_оплаты;
			}
			set
			{
				if ((this._Дата_док_оплаты != value))
				{
					this._Дата_док_оплаты = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Сумма", DbType="Money")]
		public System.Nullable<decimal> Сумма
		{
			get
			{
				return this._Сумма;
			}
			set
			{
				if ((this._Сумма != value))
				{
					this._Сумма = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEL", DbType="Bit NOT NULL")]
		public bool DEL
		{
			get
			{
				return this._DEL;
			}
			set
			{
				if ((this._DEL != value))
				{
					this._DEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Предоплачено", DbType="Bit")]
		public System.Nullable<bool> Предоплачено
		{
			get
			{
				return this._Предоплачено;
			}
			set
			{
				if ((this._Предоплачено != value))
				{
					this._Предоплачено = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата оплаты]", Storage="_Дата_оплаты", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_оплаты
		{
			get
			{
				return this._Дата_оплаты;
			}
			set
			{
				if ((this._Дата_оплаты != value))
				{
					this._Дата_оплаты = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_Предоплата")]
	public partial class view_Предоплата
	{
		
		private int _ID;
		
		private System.Nullable<System.DateTime> _Дата_предоплаты;
		
		private string _Лицо_которому_реализ_товар;
		
		private string _Наим_док_оплаты;
		
		private string _Номер_док_оплаты;
		
		private System.Nullable<System.DateTime> _Дата_док_оплаты;
		
		private System.Nullable<decimal> _Сумма_предоплаты;
		
		private string _Наим_валюты;
		
		private System.Nullable<decimal> _Сумма_в_валюте;
		
		private string _Наим_док_отгрузки;
		
		private string _Номер_док_отгрузки;
		
		private System.Nullable<System.DateTime> _Дата_док_отгрузки;
		
		private System.Nullable<bool> _Предоплачено;
		
		private bool _DEL;
		
		private System.Nullable<decimal> _Сумма;
		
		private System.Nullable<System.DateTime> _Дата_отгрузки;
		
		public view_Предоплата()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата предоплаты]", Storage="_Дата_предоплаты", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_предоплаты
		{
			get
			{
				return this._Дата_предоплаты;
			}
			set
			{
				if ((this._Дата_предоплаты != value))
				{
					this._Дата_предоплаты = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Лицо которому реализ товар]", Storage="_Лицо_которому_реализ_товар", DbType="VarChar(50)")]
		public string Лицо_которому_реализ_товар
		{
			get
			{
				return this._Лицо_которому_реализ_товар;
			}
			set
			{
				if ((this._Лицо_которому_реализ_товар != value))
				{
					this._Лицо_которому_реализ_товар = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Наим док оплаты]", Storage="_Наим_док_оплаты", DbType="VarChar(100)")]
		public string Наим_док_оплаты
		{
			get
			{
				return this._Наим_док_оплаты;
			}
			set
			{
				if ((this._Наим_док_оплаты != value))
				{
					this._Наим_док_оплаты = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Номер док оплаты]", Storage="_Номер_док_оплаты", DbType="VarChar(30)")]
		public string Номер_док_оплаты
		{
			get
			{
				return this._Номер_док_оплаты;
			}
			set
			{
				if ((this._Номер_док_оплаты != value))
				{
					this._Номер_док_оплаты = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата док оплаты]", Storage="_Дата_док_оплаты", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_док_оплаты
		{
			get
			{
				return this._Дата_док_оплаты;
			}
			set
			{
				if ((this._Дата_док_оплаты != value))
				{
					this._Дата_док_оплаты = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Сумма предоплаты]", Storage="_Сумма_предоплаты", DbType="Money")]
		public System.Nullable<decimal> Сумма_предоплаты
		{
			get
			{
				return this._Сумма_предоплаты;
			}
			set
			{
				if ((this._Сумма_предоплаты != value))
				{
					this._Сумма_предоплаты = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Наим валюты]", Storage="_Наим_валюты", DbType="VarChar(50)")]
		public string Наим_валюты
		{
			get
			{
				return this._Наим_валюты;
			}
			set
			{
				if ((this._Наим_валюты != value))
				{
					this._Наим_валюты = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Сумма в валюте]", Storage="_Сумма_в_валюте", DbType="Money")]
		public System.Nullable<decimal> Сумма_в_валюте
		{
			get
			{
				return this._Сумма_в_валюте;
			}
			set
			{
				if ((this._Сумма_в_валюте != value))
				{
					this._Сумма_в_валюте = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Наим док отгрузки]", Storage="_Наим_док_отгрузки", DbType="VarChar(100)")]
		public string Наим_док_отгрузки
		{
			get
			{
				return this._Наим_док_отгрузки;
			}
			set
			{
				if ((this._Наим_док_отгрузки != value))
				{
					this._Наим_док_отгрузки = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Номер док отгрузки]", Storage="_Номер_док_отгрузки", DbType="VarChar(30)")]
		public string Номер_док_отгрузки
		{
			get
			{
				return this._Номер_док_отгрузки;
			}
			set
			{
				if ((this._Номер_док_отгрузки != value))
				{
					this._Номер_док_отгрузки = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата док отгрузки]", Storage="_Дата_док_отгрузки", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_док_отгрузки
		{
			get
			{
				return this._Дата_док_отгрузки;
			}
			set
			{
				if ((this._Дата_док_отгрузки != value))
				{
					this._Дата_док_отгрузки = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Предоплачено", DbType="Bit")]
		public System.Nullable<bool> Предоплачено
		{
			get
			{
				return this._Предоплачено;
			}
			set
			{
				if ((this._Предоплачено != value))
				{
					this._Предоплачено = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEL", DbType="Bit NOT NULL")]
		public bool DEL
		{
			get
			{
				return this._DEL;
			}
			set
			{
				if ((this._DEL != value))
				{
					this._DEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Сумма", DbType="Money")]
		public System.Nullable<decimal> Сумма
		{
			get
			{
				return this._Сумма;
			}
			set
			{
				if ((this._Сумма != value))
				{
					this._Сумма = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата отгрузки]", Storage="_Дата_отгрузки", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_отгрузки
		{
			get
			{
				return this._Дата_отгрузки;
			}
			set
			{
				if ((this._Дата_отгрузки != value))
				{
					this._Дата_отгрузки = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Кредитор")]
	public partial class Кредитор : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Название;
		
		private System.Nullable<decimal> _Сумма_бр;
		
		private string _Номер_договора;
		
		private string _Предмет_договора;
		
		private System.Nullable<System.DateTime> _Дата_договора;
		
		private string _Наим_валюты;
		
		private System.Nullable<decimal> _Сумма_в_валюте;
		
		private bool _DEL;
		
		private string _Док_задолж_Наим;
		
		private string _Док_задолж_Номер;
		
		private System.Nullable<System.DateTime> _Док_задолж_Дата;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnНазваниеChanging(string value);
    partial void OnНазваниеChanged();
    partial void OnСумма_брChanging(System.Nullable<decimal> value);
    partial void OnСумма_брChanged();
    partial void OnНомер_договораChanging(string value);
    partial void OnНомер_договораChanged();
    partial void OnПредмет_договораChanging(string value);
    partial void OnПредмет_договораChanged();
    partial void OnДата_договораChanging(System.Nullable<System.DateTime> value);
    partial void OnДата_договораChanged();
    partial void OnНаим_валютыChanging(string value);
    partial void OnНаим_валютыChanged();
    partial void OnСумма_в_валютеChanging(System.Nullable<decimal> value);
    partial void OnСумма_в_валютеChanged();
    partial void OnDELChanging(bool value);
    partial void OnDELChanged();
    partial void OnДок_задолж_НаимChanging(string value);
    partial void OnДок_задолж_НаимChanged();
    partial void OnДок_задолж_НомерChanging(string value);
    partial void OnДок_задолж_НомерChanged();
    partial void OnДок_задолж_ДатаChanging(System.Nullable<System.DateTime> value);
    partial void OnДок_задолж_ДатаChanged();
    #endregion
		
		public Кредитор()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Название", DbType="VarChar(80)")]
		public string Название
		{
			get
			{
				return this._Название;
			}
			set
			{
				if ((this._Название != value))
				{
					this.OnНазваниеChanging(value);
					this.SendPropertyChanging();
					this._Название = value;
					this.SendPropertyChanged("Название");
					this.OnНазваниеChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Сумма_бр", DbType="Money")]
		public System.Nullable<decimal> Сумма_бр
		{
			get
			{
				return this._Сумма_бр;
			}
			set
			{
				if ((this._Сумма_бр != value))
				{
					this.OnСумма_брChanging(value);
					this.SendPropertyChanging();
					this._Сумма_бр = value;
					this.SendPropertyChanged("Сумма_бр");
					this.OnСумма_брChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Номер_договора", DbType="VarChar(20)")]
		public string Номер_договора
		{
			get
			{
				return this._Номер_договора;
			}
			set
			{
				if ((this._Номер_договора != value))
				{
					this.OnНомер_договораChanging(value);
					this.SendPropertyChanging();
					this._Номер_договора = value;
					this.SendPropertyChanged("Номер_договора");
					this.OnНомер_договораChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Предмет_договора", DbType="VarChar(200)")]
		public string Предмет_договора
		{
			get
			{
				return this._Предмет_договора;
			}
			set
			{
				if ((this._Предмет_договора != value))
				{
					this.OnПредмет_договораChanging(value);
					this.SendPropertyChanging();
					this._Предмет_договора = value;
					this.SendPropertyChanged("Предмет_договора");
					this.OnПредмет_договораChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Дата_договора", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_договора
		{
			get
			{
				return this._Дата_договора;
			}
			set
			{
				if ((this._Дата_договора != value))
				{
					this.OnДата_договораChanging(value);
					this.SendPropertyChanging();
					this._Дата_договора = value;
					this.SendPropertyChanged("Дата_договора");
					this.OnДата_договораChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Наим_валюты", DbType="VarChar(50)")]
		public string Наим_валюты
		{
			get
			{
				return this._Наим_валюты;
			}
			set
			{
				if ((this._Наим_валюты != value))
				{
					this.OnНаим_валютыChanging(value);
					this.SendPropertyChanging();
					this._Наим_валюты = value;
					this.SendPropertyChanged("Наим_валюты");
					this.OnНаим_валютыChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Сумма_в_валюте", DbType="Money")]
		public System.Nullable<decimal> Сумма_в_валюте
		{
			get
			{
				return this._Сумма_в_валюте;
			}
			set
			{
				if ((this._Сумма_в_валюте != value))
				{
					this.OnСумма_в_валютеChanging(value);
					this.SendPropertyChanging();
					this._Сумма_в_валюте = value;
					this.SendPropertyChanged("Сумма_в_валюте");
					this.OnСумма_в_валютеChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEL", DbType="Bit NOT NULL")]
		public bool DEL
		{
			get
			{
				return this._DEL;
			}
			set
			{
				if ((this._DEL != value))
				{
					this.OnDELChanging(value);
					this.SendPropertyChanging();
					this._DEL = value;
					this.SendPropertyChanged("DEL");
					this.OnDELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Док_задолж_Наим", DbType="VarChar(100)")]
		public string Док_задолж_Наим
		{
			get
			{
				return this._Док_задолж_Наим;
			}
			set
			{
				if ((this._Док_задолж_Наим != value))
				{
					this.OnДок_задолж_НаимChanging(value);
					this.SendPropertyChanging();
					this._Док_задолж_Наим = value;
					this.SendPropertyChanged("Док_задолж_Наим");
					this.OnДок_задолж_НаимChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Док_задолж_Номер", DbType="VarChar(30)")]
		public string Док_задолж_Номер
		{
			get
			{
				return this._Док_задолж_Номер;
			}
			set
			{
				if ((this._Док_задолж_Номер != value))
				{
					this.OnДок_задолж_НомерChanging(value);
					this.SendPropertyChanging();
					this._Док_задолж_Номер = value;
					this.SendPropertyChanged("Док_задолж_Номер");
					this.OnДок_задолж_НомерChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Док_задолж_Дата", DbType="DateTime")]
		public System.Nullable<System.DateTime> Док_задолж_Дата
		{
			get
			{
				return this._Док_задолж_Дата;
			}
			set
			{
				if ((this._Док_задолж_Дата != value))
				{
					this.OnДок_задолж_ДатаChanging(value);
					this.SendPropertyChanging();
					this._Док_задолж_Дата = value;
					this.SendPropertyChanged("Док_задолж_Дата");
					this.OnДок_задолж_ДатаChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
