#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KUDIR")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertВыручка(Выручка instance);
    partial void UpdateВыручка(Выручка instance);
    partial void DeleteВыручка(Выручка instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::Reports.Properties.Settings.Default.KUDIRConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Выручка> Выручкаs
		{
			get
			{
				return this.GetTable<Выручка>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Выручка")]
	public partial class Выручка : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<decimal> _Выручка_от_реализации;
		
		private System.Nullable<decimal> _Внереализационные_доходы;
		
		private string _Содержание_операции;
		
		private System.Nullable<System.DateTime> _Дата_записи;
		
		private int _ID;
		
		private bool _DEL;
		
		private string _Док_выручка_Наим;
		
		private string _Док_выручка_Номер;
		
		private System.Nullable<System.DateTime> _Док_выручка_Дата;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnВыручка_от_реализацииChanging(System.Nullable<decimal> value);
    partial void OnВыручка_от_реализацииChanged();
    partial void OnВнереализационные_доходыChanging(System.Nullable<decimal> value);
    partial void OnВнереализационные_доходыChanged();
    partial void OnСодержание_операцииChanging(string value);
    partial void OnСодержание_операцииChanged();
    partial void OnДата_записиChanging(System.Nullable<System.DateTime> value);
    partial void OnДата_записиChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDELChanging(bool value);
    partial void OnDELChanged();
    partial void OnДок_выручка_НаимChanging(string value);
    partial void OnДок_выручка_НаимChanged();
    partial void OnДок_выручка_НомерChanging(string value);
    partial void OnДок_выручка_НомерChanged();
    partial void OnДок_выручка_ДатаChanging(System.Nullable<System.DateTime> value);
    partial void OnДок_выручка_ДатаChanged();
    #endregion
		
		public Выручка()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Выручка_от_реализации", DbType="Money")]
		public System.Nullable<decimal> Выручка_от_реализации
		{
			get
			{
				return this._Выручка_от_реализации;
			}
			set
			{
				if ((this._Выручка_от_реализации != value))
				{
					this.OnВыручка_от_реализацииChanging(value);
					this.SendPropertyChanging();
					this._Выручка_от_реализации = value;
					this.SendPropertyChanged("Выручка_от_реализации");
					this.OnВыручка_от_реализацииChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Внереализационные_доходы", DbType="Money")]
		public System.Nullable<decimal> Внереализационные_доходы
		{
			get
			{
				return this._Внереализационные_доходы;
			}
			set
			{
				if ((this._Внереализационные_доходы != value))
				{
					this.OnВнереализационные_доходыChanging(value);
					this.SendPropertyChanging();
					this._Внереализационные_доходы = value;
					this.SendPropertyChanged("Внереализационные_доходы");
					this.OnВнереализационные_доходыChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Содержание_операции", DbType="VarChar(80)")]
		public string Содержание_операции
		{
			get
			{
				return this._Содержание_операции;
			}
			set
			{
				if ((this._Содержание_операции != value))
				{
					this.OnСодержание_операцииChanging(value);
					this.SendPropertyChanging();
					this._Содержание_операции = value;
					this.SendPropertyChanged("Содержание_операции");
					this.OnСодержание_операцииChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Дата_записи", DbType="DateTime")]
		public System.Nullable<System.DateTime> Дата_записи
		{
			get
			{
				return this._Дата_записи;
			}
			set
			{
				if ((this._Дата_записи != value))
				{
					this.OnДата_записиChanging(value);
					this.SendPropertyChanging();
					this._Дата_записи = value;
					this.SendPropertyChanged("Дата_записи");
					this.OnДата_записиChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEL", DbType="Bit NOT NULL")]
		public bool DEL
		{
			get
			{
				return this._DEL;
			}
			set
			{
				if ((this._DEL != value))
				{
					this.OnDELChanging(value);
					this.SendPropertyChanging();
					this._DEL = value;
					this.SendPropertyChanged("DEL");
					this.OnDELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Док_выручка_Наим", DbType="VarChar(100)")]
		public string Док_выручка_Наим
		{
			get
			{
				return this._Док_выручка_Наим;
			}
			set
			{
				if ((this._Док_выручка_Наим != value))
				{
					this.OnДок_выручка_НаимChanging(value);
					this.SendPropertyChanging();
					this._Док_выручка_Наим = value;
					this.SendPropertyChanged("Док_выручка_Наим");
					this.OnДок_выручка_НаимChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Док_выручка_Номер", DbType="VarChar(30)")]
		public string Док_выручка_Номер
		{
			get
			{
				return this._Док_выручка_Номер;
			}
			set
			{
				if ((this._Док_выручка_Номер != value))
				{
					this.OnДок_выручка_НомерChanging(value);
					this.SendPropertyChanging();
					this._Док_выручка_Номер = value;
					this.SendPropertyChanged("Док_выручка_Номер");
					this.OnДок_выручка_НомерChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Док_выручка_Дата", DbType="DateTime")]
		public System.Nullable<System.DateTime> Док_выручка_Дата
		{
			get
			{
				return this._Док_выручка_Дата;
			}
			set
			{
				if ((this._Док_выручка_Дата != value))
				{
					this.OnДок_выручка_ДатаChanging(value);
					this.SendPropertyChanging();
					this._Док_выручка_Дата = value;
					this.SendPropertyChanged("Док_выручка_Дата");
					this.OnДок_выручка_ДатаChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
